// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_registry! {
    pub enum EnchantmentEffectComponentType;
    DamageProtection = "minecraft:damage_protection",
    DamageImmunity = "minecraft:damage_immunity",
    Damage = "minecraft:damage",
    SmashDamagePerFallenBlock = "minecraft:smash_damage_per_fallen_block",
    Knockback = "minecraft:knockback",
    ArmorEffectiveness = "minecraft:armor_effectiveness",
    PostAttack = "minecraft:post_attack",
    PostPiercingAttack = "minecraft:post_piercing_attack",
    HitBlock = "minecraft:hit_block",
    ItemDamage = "minecraft:item_damage",
    EquipmentDrops = "minecraft:equipment_drops",
    LocationChanged = "minecraft:location_changed",
    Tick = "minecraft:tick",
    AmmoUse = "minecraft:ammo_use",
    ProjectilePiercing = "minecraft:projectile_piercing",
    ProjectileSpawned = "minecraft:projectile_spawned",
    ProjectileSpread = "minecraft:projectile_spread",
    ProjectileCount = "minecraft:projectile_count",
    TridentReturnAcceleration = "minecraft:trident_return_acceleration",
    FishingTimeReduction = "minecraft:fishing_time_reduction",
    FishingLuckBonus = "minecraft:fishing_luck_bonus",
    BlockExperience = "minecraft:block_experience",
    MobExperience = "minecraft:mob_experience",
    RepairWithXp = "minecraft:repair_with_xp",
    Attributes = "minecraft:attributes",
    CrossbowChargeTime = "minecraft:crossbow_charge_time",
    CrossbowChargingSounds = "minecraft:crossbow_charging_sounds",
    TridentSound = "minecraft:trident_sound",
    PreventEquipmentDrop = "minecraft:prevent_equipment_drop",
    PreventArmorChange = "minecraft:prevent_armor_change",
    TridentSpinAttackStrength = "minecraft:trident_spin_attack_strength",
}
