[package]
name = "mcrs_minecraft_core"
description = "Positions, directions, Mth, ResourceLocation, ResourceKey and TagKey"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
bevy_ecs = { workspace = true, optional = true }
bevy_math.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
mcrs_minecraft_core_macros.workspace = true

[features]
default = ["bevy"]
bevy = ["dep:bevy_ecs"]
