[package]
name = "mcrs_minecraft_core"
description = "Core types: ResourceLocation, StaticRegistry, TagFile, AppState"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
bevy_app = { workspace = true, optional = true }
bevy_ecs = { workspace = true, optional = true }
bevy_asset = { workspace = true, optional = true }
bevy_reflect = { workspace = true, optional = true }
bevy_state = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
mcrs_minecraft_core_macros.workspace = true
mcrs_minecraft_nbt.workspace = true
thiserror.workspace = true
tracing.workspace = true

[features]
default = ["bevy"]
bevy = ["dep:bevy_app", "dep:bevy_ecs", "dep:bevy_asset", "dep:bevy_reflect", "dep:bevy_state"]
