[package]
name = "mcrs_minecraft_protocol"
description = "Protocol library for Minecraft: Java Edition"
readme = "README.md"
version.workspace = true
edition.workspace = true

[dependencies]
mcrs_minecraft_registry.workspace = true
mcrs_minecraft_profile.workspace = true
mcrs_minecraft_text.workspace = true
mcrs_minecraft_item_component.workspace = true
mcrs_minecraft_chunk.workspace = true
mcrs_minecraft_core.workspace = true
bevy_math.workspace = true
mcrs_minecraft_nbt.workspace = true
mcrs_minecraft_protocol_macros.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
byteorder.workspace = true
uuid = { workspace = true, features = ["serde"] }
tracing.workspace = true
bytes.workspace = true
bitfield-struct.workspace = true
derive_more = { workspace = true, features = ["from", "into", "deref", "deref_mut", "as_ref"] }
flate2.workspace = true

[dev-dependencies]
rand.workspace = true
serde_json.workspace = true
