[package]
name = "mcrs_minecraft_decoration"
description = "mcrs_minecraft_decoration"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
bevy_math.workspace = true
fixedbitset.workspace = true
mcrs_minecraft_nbt.workspace = true
mcrs_minecraft_random.workspace = true
mcrs_minecraft_worldgen = { workspace = true, default-features = false }
mcrs_voxel_math.workspace = true
rustc-hash.workspace = true
mcrs_voxel_storage.workspace = true
serde.workspace = true

[dev-dependencies]
bytes.workspace = true
serde_json.workspace = true
mcrs_minecraft_worldgen = { workspace = true, default-features = false, features = ["corpus", "test-support"] }
