[package]
name = "mcrs_minecraft_worldgen_structure"
description = "Structures, structure sets, template pools, jigsaw assembly and structure placement"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_value_provider.workspace = true
mcrs_minecraft_block.workspace = true
mcrs_minecraft_biome.workspace = true
mcrs_minecraft_block_predicate.workspace = true
fixedbitset.workspace = true
mcrs_minecraft_entity.workspace = true
mcrs_minecraft_item.workspace = true
bevy_math.workspace = true
mcrs_minecraft_chunk.workspace = true
mcrs_minecraft_core.workspace = true
mcrs_minecraft_nbt.workspace = true
mcrs_minecraft_random.workspace = true
mcrs_minecraft_registry.workspace = true
mcrs_minecraft_worldgen_density.workspace = true
mcrs_minecraft_worldgen_feature.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
bytes.workspace = true
mcrs_minecraft_registry = { workspace = true, features = ["test-support"] }
mcrs_minecraft_worldgen_testing.workspace = true
