[package]
name = "mcrs_minecraft_worldgen_structure"
description = "Structures, structure sets, template pools, jigsaw assembly and structure placement"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
bevy_math.workspace = true
mcrs_minecraft_chunk.workspace = true
mcrs_minecraft_core.workspace = true
mcrs_minecraft_nbt.workspace = true
mcrs_minecraft_random.workspace = true
mcrs_minecraft_worldgen_density.workspace = true
mcrs_minecraft_worldgen_feature.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
bytes.workspace = true
mcrs_minecraft_worldgen_testing.workspace = true
