use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Folders whose files with the given extension are enumerated at compile time
/// and exposed at runtime as `&[&str]` slices in the generated module. Only
/// what no registry names stays here: structure templates are not a registry,
/// so nothing but a listing can find them.
const REGISTRY_FOLDERS: &[(&str, &str, &str)] = &[("TEMPLATE", "minecraft/structure", "nbt")];

fn collect_files(dir: &Path, assets_root: &Path, extension: &str, out: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, assets_root, extension, out);
        } else if path.extension().and_then(|s| s.to_str()) == Some(extension)
            && let Ok(relative) = path.strip_prefix(assets_root)
        {
            out.push(relative.to_string_lossy().replace('\\', "/"));
        }
    }
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let assets_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crate is two levels below workspace root")
        .join("assets");

    println!("cargo:rerun-if-changed=build.rs");

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit by hand.\n\n");

    for (const_name, folder, extension) in REGISTRY_FOLDERS {
        let folder_abs = assets_root.join(folder);
        let mut files = Vec::new();
        collect_files(&folder_abs, &assets_root, extension, &mut files);
        files.sort();
        println!("cargo:rerun-if-changed={}", folder_abs.display());

        code.push_str(&format!(
            "pub const FOLDER_{const_name}: &str = \"{folder}\";\n"
        ));
        code.push_str(&format!("pub const FILES_{const_name}: &[&str] = &[\n"));
        for f in &files {
            code.push_str(&format!("    \"{f}\",\n"));
        }
        code.push_str("];\n\n");
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("registry_files.rs");
    fs::write(&out_file, code).expect("write registry_files.rs");
}
