[package]
name = "mcrs_minecraft_world"
description = "Vanilla Minecraft block/item type vocabulary and static registries"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_item.workspace = true
mcrs_minecraft_dimension.workspace = true
mcrs_minecraft_biome.workspace = true
mcrs_minecraft_block.workspace = true
mcrs_minecraft_environment.workspace = true
mcrs_minecraft_assets.workspace = true
mcrs_minecraft_registry = { workspace = true, features = ["bevy"] }
mcrs_minecraft_core = { workspace = true, features = ["bevy"] }
mcrs_minecraft_nbt.workspace = true
mcrs_minecraft_protocol = { workspace = true, features = ["bevy"] }
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_asset.workspace = true
bevy_state.workspace = true
bevy_tasks.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
bevy_reflect.workspace = true
thiserror.workspace = true
mcrs_minecraft_worldgen = { workspace = true, features = ["bevy", "fast"] }
mcrs_minecraft_worldgen_feature.workspace = true
bevy_math.workspace = true
uuid.workspace = true

[dev-dependencies]
bytes.workspace = true
mcrs_minecraft_worldgen_testing.workspace = true
