[package]
name = "mcrs_minecraft_dimension"
description = "The dimension and dimension type registry values"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_value_provider.workspace = true
mcrs_minecraft_block.workspace = true
mcrs_minecraft_core.workspace = true
mcrs_minecraft_registry.workspace = true
serde.workspace = true
