[package]
name = "mcrs_minecraft_level"
description = "Chunk and column entities, dimensions, tickets, area of interest, sessions, the server loop, block updates and explosions"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_item.workspace = true
mcrs_minecraft_protocol.workspace = true
mcrs_minecraft_world.workspace = true
mcrs_minecraft_block.workspace = true
bevy_app.workspace = true
bevy_asset.workspace = true
bevy_derive.workspace = true
bevy_ecs.workspace = true
bevy_math.workspace = true
bevy_platform.workspace = true
bevy_time.workspace = true
bevy_utils.workspace = true
bitflags = "2.10.0"
flume.workspace = true
indexmap.workspace = true
mcrs_minecraft_chunk = { workspace = true, features = ["bevy"] }
mcrs_minecraft_core = { workspace = true, features = ["bevy"] }
mcrs_minecraft_random.workspace = true
mcrs_minecraft_registry = { workspace = true, features = ["bevy"] }
rand.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }

[features]
telemetry-tracy = []
