use super::Piece::*;
use super::Pool;
use crate::keys::processors;
use mcrs_minecraft_core::rl;
use mcrs_minecraft_worldgen_feature::template::Projection::*;

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    Pool {
        name: rl!("minecraft:trail_ruins/buildings"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_hall_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_hall_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_hall_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_hall_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_hall_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/large_room_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/large_room_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/large_room_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/large_room_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/large_room_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/one_room_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/one_room_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/one_room_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/one_room_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/one_room_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trail_ruins/buildings/grouped"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_full_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_full_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_full_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_full_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_full_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_lower_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_lower_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_lower_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_lower_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_lower_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_upper_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_upper_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_upper_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_upper_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_upper_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_room_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_room_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_room_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_room_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/buildings/group_room_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trail_ruins/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trail_ruins/decor/decor_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/decor/decor_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/decor/decor_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/decor/decor_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/decor/decor_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/decor/decor_6"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/decor/decor_7"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trail_ruins/roads"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trail_ruins/roads/long_road_end"), processors::TRAIL_RUINS_ROADS_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/roads/road_end_1"), processors::TRAIL_RUINS_ROADS_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/roads/road_section_1"), processors::TRAIL_RUINS_ROADS_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/roads/road_section_2"), processors::TRAIL_RUINS_ROADS_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/roads/road_section_3"), processors::TRAIL_RUINS_ROADS_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/roads/road_section_4"), processors::TRAIL_RUINS_ROADS_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/roads/road_spacer_1"), processors::TRAIL_RUINS_ROADS_ARCHAEOLOGY), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trail_ruins/tower"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trail_ruins/tower/additions"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trail_ruins/tower/hall_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/hall_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/hall_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/hall_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/hall_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/large_hall_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/large_hall_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/large_hall_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/large_hall_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/large_hall_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/one_room_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/one_room_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/one_room_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/one_room_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/one_room_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/platform_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/platform_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/platform_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/platform_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/platform_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/stable_1"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/stable_2"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/stable_3"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/stable_4"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/stable_5"), processors::TRAIL_RUINS_HOUSES_ARCHAEOLOGY), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trail_ruins/tower/tower_top"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_top_1"), processors::TRAIL_RUINS_TOWER_TOP_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_top_2"), processors::TRAIL_RUINS_TOWER_TOP_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_top_3"), processors::TRAIL_RUINS_TOWER_TOP_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_top_4"), processors::TRAIL_RUINS_TOWER_TOP_ARCHAEOLOGY), 1),
            (SingleWith(rl!("minecraft:trail_ruins/tower/tower_top_5"), processors::TRAIL_RUINS_TOWER_TOP_ARCHAEOLOGY), 1),
        ],
    },
];
