use super::Piece::*;
use super::Pool;
use crate::keys::processors;
use mcrs_minecraft_core::rl;
use mcrs_minecraft_worldgen_feature::template::Projection::*;

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    Pool {
        name: rl!("minecraft:trial_chambers/atrium"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/corridor/atrium/bogged_relief")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/atrium/breeze_relief")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/atrium/spiral_relief")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/atrium/spider_relief")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/atrium/grand_staircase_1")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/atrium/grand_staircase_2")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/atrium/grand_staircase_3")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chamber/addon"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/chamber/addon/full_stacked_walkway")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/full_stacked_walkway_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/full_corner_column")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/grate_bridge")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/hanging_platform")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/short_grate_platform")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/short_platform")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/lower_staircase_down")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/walkway_with_bridge_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/addon/c1_breeze")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chamber/assembly"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/full_column")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/cover_1")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/cover_2")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/cover_3")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/cover_4")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/cover_5")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/cover_6")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/cover_7")), 5),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/platform_1")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/spawner_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/hanging_1")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/hanging_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/hanging_3")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/hanging_4")), 2),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/hanging_5")), 4),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/left_staircase_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/left_staircase_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/left_staircase_3")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/right_staircase_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/right_staircase_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/assembly/right_staircase_3")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chamber/end"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trial_chambers/corridor/end_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/end_2"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chamber/entrance_cap"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trial_chambers/chamber/entrance_cap"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chamber/eruption"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/center_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/breeze_slice_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/slice_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/slice_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/slice_3")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/quadrant_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/quadrant_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/quadrant_3")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/quadrant_4")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/eruption/quadrant_5")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chamber/pedestal"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/center_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/slice_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/slice_2")), 3),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/slice_3")), 3),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/slice_4")), 3),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/slice_5")), 3),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/ominous_slice_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/quadrant_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/quadrant_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/pedestal/quadrant_3")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/quadrant_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/quadrant_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/quadrant_3")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/quadrant_4")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chamber/slanted"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/center")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/hallway_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/hallway_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/hallway_3")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/quadrant_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/quadrant_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/quadrant_3")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/quadrant_4")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/ramp_1")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/ramp_2")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/ramp_3")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/ramp_4")), 1),
            (Single(rl!("minecraft:trial_chambers/chamber/slanted/ominous_upper_arm_1")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chambers/end"),
        fallback: rl!("minecraft:trial_chambers/hallway/fallback"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trial_chambers/chamber/chamber_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/assembly"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/eruption"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/slanted"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chests/contents/supply"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/chests/supply")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/chests/supply"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/chests/connectors/supply")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/corridor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/corridor/second_plate")), 1),
            (SingleWith(rl!("minecraft:trial_chambers/intersection/intersection_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/intersection/intersection_2"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/intersection/intersection_3"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/first_plate")), 1),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/atrium_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/entrance_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/entrance_2"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/entrance_3"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/corridor/slices"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (SingleWith(rl!("minecraft:trial_chambers/corridor/straight_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/straight_2"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 2),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/straight_3"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 2),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/straight_4"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 2),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/straight_5"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 2),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/straight_6"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 2),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/straight_7"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/corridor/straight_8"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 2),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/corridors/addon/lower"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Empty, 8),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/staircase")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/wall")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/ladder_to_middle")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/arrow_dispenser")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/bridge_lower")), 2),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/corridors/addon/middle"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Empty, 8),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/open_walkway")), 2),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/walled_walkway")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/corridors/addon/middle_upper"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Empty, 6),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/open_walkway_upper")), 2),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/chandelier_upper")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/decoration_upper")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/head_upper")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/reward_upper")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Empty, 22),
            (Single(rl!("minecraft:trial_chambers/decor/empty_pot")), 2),
            (Single(rl!("minecraft:trial_chambers/decor/dead_bush_pot")), 2),
            (Single(rl!("minecraft:trial_chambers/decor/undecorated_pot")), 10),
            (Single(rl!("minecraft:trial_chambers/decor/flow_pot")), 1),
            (Single(rl!("minecraft:trial_chambers/decor/guster_pot")), 1),
            (Single(rl!("minecraft:trial_chambers/decor/scrape_pot")), 1),
            (Single(rl!("minecraft:trial_chambers/decor/candle_1")), 1),
            (Single(rl!("minecraft:trial_chambers/decor/candle_2")), 1),
            (Single(rl!("minecraft:trial_chambers/decor/candle_3")), 1),
            (Single(rl!("minecraft:trial_chambers/decor/candle_4")), 1),
            (Single(rl!("minecraft:trial_chambers/decor/barrel")), 2),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/decor/bed"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/decor/white_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/light_gray_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/gray_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/black_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/brown_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/red_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/orange_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/yellow_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/lime_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/green_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/cyan_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/light_blue_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/blue_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/purple_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/magenta_bed")), 3),
            (Single(rl!("minecraft:trial_chambers/decor/pink_bed")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/decor/chamber"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Empty, 4),
            (Single(rl!("minecraft:trial_chambers/decor/undecorated_pot")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/decor/disposal"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/decor/disposal")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/dispensers/chamber"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Empty, 1),
            (Single(rl!("minecraft:trial_chambers/dispensers/chamber")), 1),
            (Single(rl!("minecraft:trial_chambers/dispensers/wall_dispenser")), 1),
            (Single(rl!("minecraft:trial_chambers/dispensers/floor_dispenser")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/entrance"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/corridor/addon/display_1")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/display_2")), 1),
            (Single(rl!("minecraft:trial_chambers/corridor/addon/display_3")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/hallway"),
        fallback: rl!("minecraft:trial_chambers/hallway/fallback"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/hallway/corridor_connector_1")), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/upper_hallway_connector"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/lower_hallway_connector"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (Single(rl!("minecraft:trial_chambers/hallway/rubble")), 1),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/chamber_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/chamber_2"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/chamber_4"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/chamber_8"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/assembly"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/eruption"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/slanted"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
            (SingleWith(rl!("minecraft:trial_chambers/chamber/pedestal"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/rubble_chamber"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 10),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/rubble_chamber_thin"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/cache_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/left_corner"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/right_corner"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/corner_staircase"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/corner_staircase_down"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/long_straight_staircase"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/long_straight_staircase_down"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/straight"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/straight_staircase"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/straight_staircase_down"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/trapped_staircase"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/encounter_1"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/encounter_2"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/encounter_3"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/encounter_4"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
            (SingleWith(rl!("minecraft:trial_chambers/hallway/encounter_5"), processors::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/hallway/fallback"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/hallway/rubble")), 1),
            (Single(rl!("minecraft:trial_chambers/hallway/rubble_chamber")), 1),
            (Single(rl!("minecraft:trial_chambers/hallway/rubble_thin")), 1),
            (Single(rl!("minecraft:trial_chambers/hallway/rubble_chamber_thin")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/reward/all"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/reward/vault")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/reward/contents/default"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/reward/vault")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/reward/ominous_vault"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/reward/ominous_vault")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/all"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/connectors/ranged")), 1),
            (Single(rl!("minecraft:trial_chambers/spawner/connectors/melee")), 1),
            (Single(rl!("minecraft:trial_chambers/spawner/connectors/small_melee")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/breeze"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/connectors/breeze")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/contents/breeze"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/breeze/breeze")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/melee"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/connectors/melee")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/melee/husk"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/melee/husk")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/melee/spider"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/melee/spider")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/melee/zombie"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/melee/zombie")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/ranged"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/connectors/ranged")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/ranged/poison_skeleton"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/ranged/poison_skeleton")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/ranged/skeleton"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/ranged/skeleton")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/ranged/stray"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/ranged/stray")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/slow_ranged"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/connectors/slow_ranged")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/slow_ranged/poison_skeleton"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/slow_ranged/poison_skeleton")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/slow_ranged/skeleton"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/slow_ranged/skeleton")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/slow_ranged/stray"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/slow_ranged/stray")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/small_melee"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/connectors/small_melee")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/small_melee/baby_zombie"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/small_melee/baby_zombie")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/small_melee/cave_spider"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/small_melee/cave_spider")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/small_melee/silverfish"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/small_melee/silverfish")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:trial_chambers/spawner/small_melee/slime"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Single(rl!("minecraft:trial_chambers/spawner/small_melee/slime")), 1),
        ],
    },
];
