use super::Piece::*;
use super::{Pool, pool, single};
use mcrs_minecraft_worldgen_feature::keys::processor_list;

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    pool("trial_chambers/atrium").dir("trial_chambers/corridor/atrium/").pieces(&[
        (single("bogged_relief"), 1),
        (single("breeze_relief"), 1),
        (single("spiral_relief"), 1),
        (single("spider_relief"), 1),
        (single("grand_staircase_").numbered(1, 3), 1),
    ]),
    pool("trial_chambers/chamber/addon").dir("trial_chambers/chamber/addon/").pieces(&[
        (single("full_stacked_walkway"), 1),
        (single("full_stacked_walkway_2"), 1),
        (single("full_corner_column"), 1),
        (single("grate_bridge"), 1),
        (single("hanging_platform"), 1),
        (single("short_grate_platform"), 1),
        (single("short_platform"), 1),
        (single("lower_staircase_down"), 1),
        (single("walkway_with_bridge_1"), 1),
        (single("c1_breeze"), 1),
    ]),
    pool("trial_chambers/chamber/assembly").dir("trial_chambers/chamber/assembly/").pieces(&[
        (single("full_column"), 2),
        (single("cover_").numbered(1, 6), 2),
        (single("cover_7"), 5),
        (single("platform_1"), 2),
        (single("spawner_1"), 1),
        (single("hanging_1"), 2),
        (single("hanging_2"), 1),
        (single("hanging_").numbered(3, 4), 2),
        (single("hanging_5"), 4),
        (single("left_staircase_").numbered(1, 3), 1),
        (single("right_staircase_").numbered(1, 3), 1),
    ]),
    pool("trial_chambers/chamber/end").dir("trial_chambers/corridor/").processors(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION).pieces(&[(single("end_").numbered(1, 2), 1)]),
    pool("trial_chambers/chamber/entrance_cap").dir("trial_chambers/chamber/").processors(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION).pieces(&[(single("entrance_cap"), 1)]),
    pool("trial_chambers/chamber/eruption").dir("trial_chambers/chamber/eruption/").pieces(&[
        (single("center_1"), 1),
        (single("breeze_slice_1"), 1),
        (single("slice_").numbered(1, 3), 1),
        (single("quadrant_").numbered(1, 5), 1),
    ]),
    pool("trial_chambers/chamber/pedestal").dir("trial_chambers/chamber/").pieces(&[
        (single("pedestal/center_1"), 1),
        (single("pedestal/slice_1"), 1),
        (single("pedestal/slice_").numbered(2, 5), 3),
        (single("pedestal/ominous_slice_1"), 1),
        (single("pedestal/quadrant_").numbered(1, 3), 1),
        (single("slanted/quadrant_").numbered(1, 4), 1),
    ]),
    pool("trial_chambers/chamber/slanted").dir("trial_chambers/chamber/slanted/").pieces(&[
        (single("center"), 1),
        (single("hallway_").numbered(1, 3), 1),
        (single("quadrant_").numbered(1, 4), 1),
        (single("ramp_").numbered(1, 4), 1),
        (single("ominous_upper_arm_1"), 1),
    ]),
    pool("trial_chambers/chambers/end").fallback("trial_chambers/hallway/fallback").dir("trial_chambers/chamber/").processors(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION).pieces(&[
        (single("chamber_1"), 1),
        (single("assembly"), 1),
        (single("eruption"), 1),
        (single("slanted"), 1),
    ]),
    pool("trial_chambers/chests/contents/supply").dir("trial_chambers/chests/").pieces(&[(single("supply"), 1)]),
    pool("trial_chambers/chests/supply").dir("trial_chambers/chests/connectors/").pieces(&[(single("supply"), 1)]),
    pool("trial_chambers/corridor").dir("trial_chambers/").pieces(&[
        (single("corridor/second_plate"), 1),
        (single("intersection/intersection_").numbered(1, 3).with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("corridor/first_plate"), 1),
        (single("corridor/atrium_1").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("corridor/entrance_").numbered(1, 3).with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
    ]),
    pool("trial_chambers/corridor/slices").dir("trial_chambers/corridor/").processors(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION).pieces(&[
        (single("straight_1"), 1),
        (single("straight_").numbered(2, 6), 2),
        (single("straight_7"), 1),
        (single("straight_8"), 2),
    ]),
    pool("trial_chambers/corridors/addon/lower").dir("trial_chambers/corridor/addon/").pieces(&[
        (Empty, 8),
        (single("staircase"), 1),
        (single("wall"), 1),
        (single("ladder_to_middle"), 1),
        (single("arrow_dispenser"), 1),
        (single("bridge_lower"), 2),
    ]),
    pool("trial_chambers/corridors/addon/middle").dir("trial_chambers/corridor/addon/").pieces(&[
        (Empty, 8),
        (single("open_walkway"), 2),
        (single("walled_walkway"), 1),
    ]),
    pool("trial_chambers/corridors/addon/middle_upper").dir("trial_chambers/corridor/addon/").pieces(&[
        (Empty, 6),
        (single("open_walkway_upper"), 2),
        (single("chandelier_upper"), 1),
        (single("decoration_upper"), 1),
        (single("head_upper"), 1),
        (single("reward_upper"), 1),
    ]),
    pool("trial_chambers/decor").dir("trial_chambers/decor/").pieces(&[
        (Empty, 22),
        (single("empty_pot"), 2),
        (single("dead_bush_pot"), 2),
        (single("undecorated_pot"), 10),
        (single("flow_pot"), 1),
        (single("guster_pot"), 1),
        (single("scrape_pot"), 1),
        (single("candle_").numbered(1, 4), 1),
        (single("barrel"), 2),
    ]),
    pool("trial_chambers/decor/bed").dir("trial_chambers/decor/").pieces(&[
        (single("white_bed"), 3),
        (single("light_gray_bed"), 3),
        (single("gray_bed"), 3),
        (single("black_bed"), 3),
        (single("brown_bed"), 3),
        (single("red_bed"), 3),
        (single("orange_bed"), 3),
        (single("yellow_bed"), 3),
        (single("lime_bed"), 3),
        (single("green_bed"), 3),
        (single("cyan_bed"), 3),
        (single("light_blue_bed"), 3),
        (single("blue_bed"), 3),
        (single("purple_bed"), 3),
        (single("magenta_bed"), 3),
        (single("pink_bed"), 1),
    ]),
    pool("trial_chambers/decor/chamber").dir("trial_chambers/decor/").pieces(&[
        (Empty, 4),
        (single("undecorated_pot"), 1),
    ]),
    pool("trial_chambers/decor/disposal").dir("trial_chambers/decor/").pieces(&[(single("disposal"), 1)]),
    pool("trial_chambers/dispensers/chamber").dir("trial_chambers/dispensers/").pieces(&[
        (Empty, 1),
        (single("chamber"), 1),
        (single("wall_dispenser"), 1),
        (single("floor_dispenser"), 1),
    ]),
    pool("trial_chambers/entrance").dir("trial_chambers/corridor/addon/").pieces(&[(single("display_").numbered(1, 3), 1)]),
    pool("trial_chambers/hallway").fallback("trial_chambers/hallway/fallback").dir("trial_chambers/").pieces(&[
        (single("hallway/corridor_connector_1"), 1),
        (single("hallway/upper_hallway_connector").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/lower_hallway_connector").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/rubble"), 1),
        (single("chamber/chamber_").numbered(1, 2).with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
        (single("chamber/chamber_4").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
        (single("chamber/chamber_8").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
        (single("chamber/assembly").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
        (single("chamber/eruption").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
        (single("chamber/slanted").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
        (single("chamber/pedestal").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 150),
        (single("hallway/rubble_chamber").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 10),
        (single("hallway/rubble_chamber_thin").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/cache_1").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/left_corner").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/right_corner").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/corner_staircase").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/corner_staircase_down").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/long_straight_staircase").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/long_straight_staircase_down").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/straight").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/straight_staircase").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/straight_staircase_down").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/trapped_staircase").with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
        (single("hallway/encounter_").numbered(1, 5).with(processor_list::TRIAL_CHAMBERS_COPPER_BULB_DEGRADATION), 1),
    ]),
    pool("trial_chambers/hallway/fallback").dir("trial_chambers/hallway/").pieces(&[
        (single("rubble"), 1),
        (single("rubble_chamber"), 1),
        (single("rubble_thin"), 1),
        (single("rubble_chamber_thin"), 1),
    ]),
    pool("trial_chambers/reward/all").dir("trial_chambers/reward/").pieces(&[(single("vault"), 1)]),
    pool("trial_chambers/reward/contents/default").dir("trial_chambers/reward/").pieces(&[(single("vault"), 1)]),
    pool("trial_chambers/reward/ominous_vault").dir("trial_chambers/reward/").pieces(&[(single("ominous_vault"), 1)]),
    pool("trial_chambers/spawner/all").dir("trial_chambers/spawner/connectors/").pieces(&[
        (single("ranged"), 1),
        (single("melee"), 1),
        (single("small_melee"), 1),
    ]),
    pool("trial_chambers/spawner/breeze").dir("trial_chambers/spawner/connectors/").pieces(&[(single("breeze"), 1)]),
    pool("trial_chambers/spawner/contents/breeze").dir("trial_chambers/spawner/breeze/").pieces(&[(single("breeze"), 1)]),
    pool("trial_chambers/spawner/melee").dir("trial_chambers/spawner/connectors/").pieces(&[(single("melee"), 1)]),
    pool("trial_chambers/spawner/melee/husk").dir("trial_chambers/spawner/melee/").pieces(&[(single("husk"), 1)]),
    pool("trial_chambers/spawner/melee/spider").dir("trial_chambers/spawner/melee/").pieces(&[(single("spider"), 1)]),
    pool("trial_chambers/spawner/melee/zombie").dir("trial_chambers/spawner/melee/").pieces(&[(single("zombie"), 1)]),
    pool("trial_chambers/spawner/ranged").dir("trial_chambers/spawner/connectors/").pieces(&[(single("ranged"), 1)]),
    pool("trial_chambers/spawner/ranged/poison_skeleton").dir("trial_chambers/spawner/ranged/").pieces(&[(single("poison_skeleton"), 1)]),
    pool("trial_chambers/spawner/ranged/skeleton").dir("trial_chambers/spawner/ranged/").pieces(&[(single("skeleton"), 1)]),
    pool("trial_chambers/spawner/ranged/stray").dir("trial_chambers/spawner/ranged/").pieces(&[(single("stray"), 1)]),
    pool("trial_chambers/spawner/slow_ranged").dir("trial_chambers/spawner/connectors/").pieces(&[(single("slow_ranged"), 1)]),
    pool("trial_chambers/spawner/slow_ranged/poison_skeleton").dir("trial_chambers/spawner/slow_ranged/").pieces(&[(single("poison_skeleton"), 1)]),
    pool("trial_chambers/spawner/slow_ranged/skeleton").dir("trial_chambers/spawner/slow_ranged/").pieces(&[(single("skeleton"), 1)]),
    pool("trial_chambers/spawner/slow_ranged/stray").dir("trial_chambers/spawner/slow_ranged/").pieces(&[(single("stray"), 1)]),
    pool("trial_chambers/spawner/small_melee").dir("trial_chambers/spawner/connectors/").pieces(&[(single("small_melee"), 1)]),
    pool("trial_chambers/spawner/small_melee/baby_zombie").dir("trial_chambers/spawner/small_melee/").pieces(&[(single("baby_zombie"), 1)]),
    pool("trial_chambers/spawner/small_melee/cave_spider").dir("trial_chambers/spawner/small_melee/").pieces(&[(single("cave_spider"), 1)]),
    pool("trial_chambers/spawner/small_melee/silverfish").dir("trial_chambers/spawner/small_melee/").pieces(&[(single("silverfish"), 1)]),
    pool("trial_chambers/spawner/small_melee/slime").dir("trial_chambers/spawner/small_melee/").pieces(&[(single("slime"), 1)]),
];
