use super::Piece::*;
use super::Pool;
use crate::keys::{placed, processors};
use mcrs_minecraft_core::rl;
use mcrs_minecraft_worldgen_feature::template::Projection::*;

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    Pool {
        name: rl!("minecraft:village/desert/camel"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/camel_spawn")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/desert_lamp_1")), 10),
            (Feature(placed::PATCH_CACTUS), 4),
            (Feature(placed::PILE_HAY), 4),
            (Empty, 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/houses"),
        fallback: rl!("minecraft:village/desert/terminators"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/houses/desert_small_house_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_small_house_2")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_small_house_3")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_small_house_4")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_small_house_5")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_small_house_6")), 1),
            (Legacy(rl!("minecraft:village/desert/houses/desert_small_house_7")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_small_house_8")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_medium_house_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_medium_house_2")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_butcher_shop_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_tool_smith_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_fletcher_house_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_shepherd_house_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_armorer_1")), 1),
            (Legacy(rl!("minecraft:village/desert/houses/desert_fisher_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_tannery_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_cartographer_house_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_library_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_mason_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_weaponsmith_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_temple_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_temple_2")), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_large_farm_1"), processors::FARM_DESERT), 11),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_farm_1"), processors::FARM_DESERT), 4),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_farm_2"), processors::FARM_DESERT), 4),
            (Legacy(rl!("minecraft:village/desert/houses/desert_animal_pen_1")), 2),
            (Legacy(rl!("minecraft:village/desert/houses/desert_animal_pen_2")), 2),
            (Empty, 5),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/streets"),
        fallback: rl!("minecraft:village/desert/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/streets/corner_01")), 3),
            (Legacy(rl!("minecraft:village/desert/streets/corner_02")), 3),
            (Legacy(rl!("minecraft:village/desert/streets/straight_01")), 4),
            (Legacy(rl!("minecraft:village/desert/streets/straight_02")), 4),
            (Legacy(rl!("minecraft:village/desert/streets/straight_03")), 3),
            (Legacy(rl!("minecraft:village/desert/streets/crossroad_01")), 3),
            (Legacy(rl!("minecraft:village/desert/streets/crossroad_02")), 3),
            (Legacy(rl!("minecraft:village/desert/streets/crossroad_03")), 3),
            (Legacy(rl!("minecraft:village/desert/streets/square_01")), 3),
            (Legacy(rl!("minecraft:village/desert/streets/square_02")), 3),
            (Legacy(rl!("minecraft:village/desert/streets/turn_01")), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/terminators"),
        fallback: rl!("minecraft:empty"),
        projection: TerrainMatching,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/terminators/terminator_01")), 1),
            (Legacy(rl!("minecraft:village/desert/terminators/terminator_02")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/town_centers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/town_centers/desert_meeting_point_1")), 98),
            (Legacy(rl!("minecraft:village/desert/town_centers/desert_meeting_point_2")), 98),
            (Legacy(rl!("minecraft:village/desert/town_centers/desert_meeting_point_3")), 49),
            (LegacyWith(rl!("minecraft:village/desert/zombie/town_centers/desert_meeting_point_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/town_centers/desert_meeting_point_2"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/town_centers/desert_meeting_point_3"), processors::ZOMBIE_DESERT), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/desert/villagers/baby")), 1),
            (Legacy(rl!("minecraft:village/desert/villagers/unemployed")), 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/zombie/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/desert/desert_lamp_1"), processors::ZOMBIE_DESERT), 10),
            (Feature(placed::PATCH_CACTUS), 4),
            (Feature(placed::PILE_HAY), 4),
            (Empty, 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/zombie/houses"),
        fallback: rl!("minecraft:village/desert/zombie/terminators"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_small_house_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_small_house_2"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_small_house_3"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_small_house_4"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_small_house_5"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_small_house_6"), processors::ZOMBIE_DESERT), 1),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_small_house_7"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_small_house_8"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_medium_house_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/zombie/houses/desert_medium_house_2"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_butcher_shop_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_tool_smith_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_fletcher_house_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_shepherd_house_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_armorer_1"), processors::ZOMBIE_DESERT), 1),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_fisher_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_tannery_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_cartographer_house_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_library_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_mason_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_weaponsmith_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_temple_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_temple_2"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_large_farm_1"), processors::ZOMBIE_DESERT), 7),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_farm_1"), processors::ZOMBIE_DESERT), 4),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_farm_2"), processors::ZOMBIE_DESERT), 4),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_animal_pen_1"), processors::ZOMBIE_DESERT), 2),
            (LegacyWith(rl!("minecraft:village/desert/houses/desert_animal_pen_2"), processors::ZOMBIE_DESERT), 2),
            (Empty, 5),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/zombie/streets"),
        fallback: rl!("minecraft:village/desert/zombie/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/zombie/streets/corner_01")), 3),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/corner_02")), 3),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/straight_01")), 4),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/straight_02")), 4),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/straight_03")), 3),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/crossroad_01")), 3),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/crossroad_02")), 3),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/crossroad_03")), 3),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/square_01")), 3),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/square_02")), 3),
            (Legacy(rl!("minecraft:village/desert/zombie/streets/turn_01")), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/zombie/terminators"),
        fallback: rl!("minecraft:empty"),
        projection: TerrainMatching,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/terminators/terminator_01")), 1),
            (Legacy(rl!("minecraft:village/desert/zombie/terminators/terminator_02")), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/desert/zombie/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/desert/zombie/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/desert/zombie/villagers/unemployed")), 10),
        ],
    },
];
