use super::Piece::*;
use super::{Pool, legacy, pool};
use crate::keys::{placed, processors};

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    pool("village/taiga/decor").dir("village/taiga/").pieces(&[
        (legacy("taiga_lamp_post_1"), 10),
        (legacy("taiga_decoration_1"), 4),
        (legacy("taiga_decoration_").numbered(2, 4), 1),
        (legacy("taiga_decoration_5"), 2),
        (legacy("taiga_decoration_6"), 1),
        (Feature(placed::SPRUCE), 4),
        (Feature(placed::PINE), 4),
        (Feature(placed::PILE_PUMPKIN), 2),
        (Feature(placed::PATCH_TAIGA_GRASS), 4),
        (Feature(placed::PATCH_BERRY_BUSH), 1),
        (Empty, 4),
    ]),
    pool("village/taiga/houses").fallback("village/taiga/terminators").dir("village/taiga/houses/").pieces(&[
        (legacy("taiga_small_house_").numbered(1, 5).with(processors::MOSSIFY_10_PERCENT), 4),
        (legacy("taiga_medium_house_").numbered(1, 4).with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_butcher_shop_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_tool_smith_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_fletcher_house_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_shepherds_house_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_armorer_house_1").with(processors::MOSSIFY_10_PERCENT), 1),
        (legacy("taiga_armorer_2").with(processors::MOSSIFY_10_PERCENT), 1),
        (legacy("taiga_fisher_cottage_1").with(processors::MOSSIFY_10_PERCENT), 3),
        (legacy("taiga_tannery_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_cartographer_house_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_library_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_masons_house_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_weaponsmith_").numbered(1, 2).with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_temple_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("taiga_large_farm_").numbered(1, 2).with(processors::FARM_TAIGA), 6),
        (legacy("taiga_small_farm_1").with(processors::MOSSIFY_10_PERCENT), 1),
        (legacy("taiga_animal_pen_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (Empty, 6),
    ]),
    pool("village/taiga/streets").fallback("village/taiga/terminators").terrain_matching().dir("village/taiga/streets/").processors(processors::STREET_SNOWY_OR_TAIGA).pieces(&[
        (legacy("corner_").padded(1, 3, 2), 2),
        (legacy("straight_").padded(1, 3, 2), 4),
        (legacy("straight_").padded(4, 5, 2), 7),
        (legacy("straight_06"), 4),
        (legacy("crossroad_").padded(1, 2, 2), 1),
        (legacy("crossroad_").padded(3, 6, 2), 2),
        (legacy("turn_01"), 3),
    ]),
    pool("village/taiga/terminators").terrain_matching().dir("village/plains/terminators/").processors(processors::STREET_SNOWY_OR_TAIGA).pieces(&[(legacy("terminator_").padded(1, 4, 2), 1)]),
    pool("village/taiga/town_centers").dir("village/taiga/").pieces(&[
        (legacy("town_centers/taiga_meeting_point_").numbered(1, 2).with(processors::MOSSIFY_10_PERCENT), 49),
        (legacy("zombie/town_centers/taiga_meeting_point_").numbered(1, 2).with(processors::ZOMBIE_TAIGA), 1),
    ]),
    pool("village/taiga/villagers").dir("village/taiga/villagers/").pieces(&[
        (legacy("nitwit"), 1),
        (legacy("baby"), 1),
        (legacy("unemployed"), 10),
    ]),
    pool("village/taiga/zombie/decor").dir("village/taiga/").pieces(&[
        (legacy("taiga_decoration_1"), 4),
        (legacy("taiga_decoration_").numbered(2, 4), 1),
        (Feature(placed::SPRUCE), 4),
        (Feature(placed::PINE), 4),
        (Feature(placed::PILE_PUMPKIN), 2),
        (Feature(placed::PATCH_TAIGA_GRASS), 4),
        (Feature(placed::PATCH_BERRY_BUSH), 1),
        (Empty, 4),
    ]),
    pool("village/taiga/zombie/houses").fallback("village/taiga/terminators").dir("village/taiga/").processors(processors::ZOMBIE_TAIGA).pieces(&[
        (legacy("zombie/houses/taiga_small_house_").numbered(1, 5), 4),
        (legacy("zombie/houses/taiga_medium_house_").numbered(1, 4), 2),
        (legacy("houses/taiga_butcher_shop_1"), 2),
        (legacy("zombie/houses/taiga_tool_smith_1"), 2),
        (legacy("houses/taiga_fletcher_house_1"), 2),
        (legacy("zombie/houses/taiga_shepherds_house_1"), 2),
        (legacy("houses/taiga_armorer_house_1"), 1),
        (legacy("zombie/houses/taiga_fisher_cottage_1"), 2),
        (legacy("houses/taiga_tannery_1"), 2),
        (legacy("zombie/houses/taiga_cartographer_house_1"), 2),
        (legacy("zombie/houses/taiga_library_1"), 2),
        (legacy("houses/taiga_masons_house_1"), 2),
        (legacy("houses/taiga_weaponsmith_1"), 2),
        (legacy("zombie/houses/taiga_weaponsmith_2"), 2),
        (legacy("zombie/houses/taiga_temple_1"), 2),
        (legacy("houses/taiga_large_farm_1"), 6),
        (legacy("zombie/houses/taiga_large_farm_2"), 6),
        (legacy("houses/taiga_small_farm_1"), 1),
        (legacy("houses/taiga_animal_pen_1"), 2),
        (Empty, 6),
    ]),
    pool("village/taiga/zombie/streets").fallback("village/taiga/terminators").terrain_matching().dir("village/taiga/zombie/streets/").processors(processors::STREET_SNOWY_OR_TAIGA).pieces(&[
        (legacy("corner_").padded(1, 3, 2), 2),
        (legacy("straight_").padded(1, 3, 2), 4),
        (legacy("straight_").padded(4, 5, 2), 7),
        (legacy("straight_06"), 4),
        (legacy("crossroad_").padded(1, 2, 2), 1),
        (legacy("crossroad_").padded(3, 6, 2), 2),
        (legacy("turn_01"), 3),
    ]),
    pool("village/taiga/zombie/villagers").dir("village/taiga/zombie/villagers/").pieces(&[
        (legacy("nitwit"), 1),
        (legacy("unemployed"), 10),
    ]),
];
