use super::Piece::*;
use super::Pool;
use crate::keys::{placed, processors};
use mcrs_minecraft_core::rl;
use mcrs_minecraft_worldgen_feature::template::Projection::*;

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    Pool {
        name: rl!("minecraft:village/snowy/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/snowy/snowy_lamp_post_01")), 4),
            (Legacy(rl!("minecraft:village/snowy/snowy_lamp_post_02")), 4),
            (Legacy(rl!("minecraft:village/snowy/snowy_lamp_post_03")), 1),
            (Feature(placed::SPRUCE), 4),
            (Feature(placed::PILE_SNOW), 4),
            (Feature(placed::PILE_ICE), 1),
            (Empty, 9),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/houses"),
        fallback: rl!("minecraft:village/snowy/terminators"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_small_house_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_small_house_2")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_small_house_3")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_small_house_4")), 3),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_small_house_5")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_small_house_6")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_small_house_7")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_small_house_8")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_medium_house_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_medium_house_2")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_medium_house_3")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_butchers_shop_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_butchers_shop_2")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_tool_smith_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_fletcher_house_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_shepherds_house_1")), 3),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_armorer_house_1")), 1),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_armorer_house_2")), 1),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_fisher_cottage")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_tannery_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_cartographer_house_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_library_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_masons_house_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_masons_house_2")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_weapon_smith_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_temple_1")), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_farm_1"), processors::FARM_SNOWY), 3),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_farm_2"), processors::FARM_SNOWY), 3),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_animal_pen_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/houses/snowy_animal_pen_2")), 2),
            (Empty, 6),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/streets"),
        fallback: rl!("minecraft:village/snowy/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/snowy/streets/corner_01"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/streets/corner_02"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/streets/corner_03"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/streets/square_01"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/streets/straight_01"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/streets/straight_02"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/streets/straight_03"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/streets/straight_04"), processors::STREET_SNOWY_OR_TAIGA), 7),
            (LegacyWith(rl!("minecraft:village/snowy/streets/straight_06"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/streets/straight_08"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/streets/crossroad_02"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/snowy/streets/crossroad_03"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/streets/crossroad_04"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/streets/crossroad_05"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/streets/crossroad_06"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/streets/turn_01"), processors::STREET_SNOWY_OR_TAIGA), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/terminators"),
        fallback: rl!("minecraft:empty"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_01"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_02"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_03"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_04"), processors::STREET_SNOWY_OR_TAIGA), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/town_centers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/snowy/town_centers/snowy_meeting_point_1")), 100),
            (Legacy(rl!("minecraft:village/snowy/town_centers/snowy_meeting_point_2")), 50),
            (Legacy(rl!("minecraft:village/snowy/town_centers/snowy_meeting_point_3")), 150),
            (Legacy(rl!("minecraft:village/snowy/zombie/town_centers/snowy_meeting_point_1")), 2),
            (Legacy(rl!("minecraft:village/snowy/zombie/town_centers/snowy_meeting_point_2")), 1),
            (Legacy(rl!("minecraft:village/snowy/zombie/town_centers/snowy_meeting_point_3")), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/trees"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Feature(placed::SPRUCE), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/snowy/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/snowy/villagers/baby")), 1),
            (Legacy(rl!("minecraft:village/snowy/villagers/unemployed")), 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/zombie/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/snowy/snowy_lamp_post_01"), processors::ZOMBIE_SNOWY), 1),
            (LegacyWith(rl!("minecraft:village/snowy/snowy_lamp_post_02"), processors::ZOMBIE_SNOWY), 1),
            (LegacyWith(rl!("minecraft:village/snowy/snowy_lamp_post_03"), processors::ZOMBIE_SNOWY), 1),
            (Feature(placed::SPRUCE), 4),
            (Feature(placed::PILE_SNOW), 4),
            (Feature(placed::PILE_ICE), 4),
            (Empty, 7),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/zombie/houses"),
        fallback: rl!("minecraft:village/snowy/terminators"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_small_house_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_small_house_2"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_small_house_3"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_small_house_4"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_small_house_5"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_small_house_6"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_small_house_7"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_small_house_8"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_medium_house_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_medium_house_2"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/houses/snowy_medium_house_3"), processors::ZOMBIE_SNOWY), 1),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_butchers_shop_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_butchers_shop_2"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_tool_smith_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_fletcher_house_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_shepherds_house_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_armorer_house_1"), processors::ZOMBIE_SNOWY), 1),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_armorer_house_2"), processors::ZOMBIE_SNOWY), 1),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_fisher_cottage"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_tannery_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_cartographer_house_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_library_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_masons_house_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_masons_house_2"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_weapon_smith_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_temple_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_farm_1"), processors::ZOMBIE_SNOWY), 3),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_farm_2"), processors::ZOMBIE_SNOWY), 3),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_animal_pen_1"), processors::ZOMBIE_SNOWY), 2),
            (LegacyWith(rl!("minecraft:village/snowy/houses/snowy_animal_pen_2"), processors::ZOMBIE_SNOWY), 2),
            (Empty, 6),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/zombie/streets"),
        fallback: rl!("minecraft:village/snowy/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/corner_01"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/corner_02"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/corner_03"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/square_01"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/straight_01"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/straight_02"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/straight_03"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/straight_04"), processors::STREET_SNOWY_OR_TAIGA), 7),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/straight_06"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/straight_08"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/crossroad_02"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/crossroad_03"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/crossroad_04"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/crossroad_05"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/crossroad_06"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/snowy/zombie/streets/turn_01"), processors::STREET_SNOWY_OR_TAIGA), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/snowy/zombie/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/snowy/zombie/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/snowy/zombie/villagers/unemployed")), 10),
        ],
    },
];
