use super::Piece::*;
use super::{Pool, legacy, pool};
use crate::keys::{placed, processors};

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    pool("village/plains/decor").dir("village/plains/").pieces(&[
        (legacy("plains_lamp_1"), 2),
        (Feature(placed::OAK), 1),
        (Feature(placed::FLOWER_PLAIN), 1),
        (Feature(placed::PILE_HAY), 1),
        (Empty, 2),
    ]),
    pool("village/plains/houses").fallback("village/plains/terminators").dir("village/plains/houses/").pieces(&[
        (legacy("plains_small_house_").numbered(1, 5).with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_small_house_6").with(processors::MOSSIFY_10_PERCENT), 1),
        (legacy("plains_small_house_7").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_small_house_8").with(processors::MOSSIFY_10_PERCENT), 3),
        (legacy("plains_medium_house_").numbered(1, 2).with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_big_house_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_butcher_shop_").numbered(1, 2).with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_tool_smith_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_fletcher_house_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_shepherds_house_1"), 2),
        (legacy("plains_armorer_house_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_fisher_cottage_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_tannery_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_cartographer_1").with(processors::MOSSIFY_10_PERCENT), 1),
        (legacy("plains_library_1").with(processors::MOSSIFY_10_PERCENT), 5),
        (legacy("plains_library_2").with(processors::MOSSIFY_10_PERCENT), 1),
        (legacy("plains_masons_house_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_weaponsmith_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_temple_").numbered(3, 4).with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_stable_1").with(processors::MOSSIFY_10_PERCENT), 2),
        (legacy("plains_stable_2"), 2),
        (legacy("plains_large_farm_1").with(processors::FARM_PLAINS), 4),
        (legacy("plains_small_farm_1").with(processors::FARM_PLAINS), 4),
        (legacy("plains_animal_pen_").numbered(1, 2), 1),
        (legacy("plains_animal_pen_3"), 5),
        (legacy("plains_accessory_1"), 1),
        (legacy("plains_meeting_point_4").with(processors::MOSSIFY_70_PERCENT), 3),
        (legacy("plains_meeting_point_5"), 1),
        (Empty, 10),
    ]),
    pool("village/plains/streets").fallback("village/plains/terminators").terrain_matching().dir("village/plains/streets/").processors(processors::STREET_PLAINS).pieces(&[
        (legacy("corner_").padded(1, 3, 2), 2),
        (legacy("straight_").padded(1, 2, 2), 4),
        (legacy("straight_").padded(3, 4, 2), 7),
        (legacy("straight_05"), 3),
        (legacy("straight_06"), 4),
        (legacy("crossroad_01"), 2),
        (legacy("crossroad_02"), 1),
        (legacy("crossroad_").padded(3, 6, 2), 2),
        (legacy("turn_01"), 3),
    ]),
    pool("village/plains/terminators").terrain_matching().dir("village/plains/terminators/").processors(processors::STREET_PLAINS).pieces(&[(legacy("terminator_").padded(1, 4, 2), 1)]),
    pool("village/plains/town_centers").dir("village/plains/").pieces(&[
        (legacy("town_centers/plains_fountain_01").with(processors::MOSSIFY_20_PERCENT), 50),
        (legacy("town_centers/plains_meeting_point_1").with(processors::MOSSIFY_20_PERCENT), 50),
        (legacy("town_centers/plains_meeting_point_2"), 50),
        (legacy("town_centers/plains_meeting_point_3").with(processors::MOSSIFY_70_PERCENT), 50),
        (legacy("zombie/town_centers/plains_fountain_01").with(processors::ZOMBIE_PLAINS), 1),
        (legacy("zombie/town_centers/plains_meeting_point_").numbered(1, 3).with(processors::ZOMBIE_PLAINS), 1),
    ]),
    pool("village/plains/trees").pieces(&[(Feature(placed::OAK), 1)]),
    pool("village/plains/villagers").dir("village/plains/villagers/").pieces(&[
        (legacy("nitwit"), 1),
        (legacy("baby"), 1),
        (legacy("unemployed"), 10),
    ]),
    pool("village/plains/zombie/decor").dir("village/plains/").processors(processors::ZOMBIE_PLAINS).pieces(&[
        (legacy("plains_lamp_1"), 1),
        (Feature(placed::OAK), 1),
        (Feature(placed::FLOWER_PLAIN), 1),
        (Feature(placed::PILE_HAY), 1),
        (Empty, 2),
    ]),
    pool("village/plains/zombie/houses").fallback("village/plains/terminators").dir("village/plains/").processors(processors::ZOMBIE_PLAINS).pieces(&[
        (legacy("zombie/houses/plains_small_house_").numbered(1, 5), 2),
        (legacy("zombie/houses/plains_small_house_6"), 1),
        (legacy("zombie/houses/plains_small_house_").numbered(7, 8), 2),
        (legacy("zombie/houses/plains_medium_house_").numbered(1, 2), 2),
        (legacy("zombie/houses/plains_big_house_1"), 2),
        (legacy("houses/plains_butcher_shop_1"), 2),
        (legacy("zombie/houses/plains_butcher_shop_2"), 2),
        (legacy("houses/plains_tool_smith_1"), 2),
        (legacy("zombie/houses/plains_fletcher_house_1"), 2),
        (legacy("zombie/houses/plains_shepherds_house_1"), 2),
        (legacy("houses/plains_armorer_house_1"), 2),
        (legacy("houses/plains_fisher_cottage_1"), 2),
        (legacy("houses/plains_tannery_1"), 2),
        (legacy("houses/plains_cartographer_1"), 1),
        (legacy("houses/plains_library_1"), 3),
        (legacy("houses/plains_library_2"), 1),
        (legacy("houses/plains_masons_house_1"), 2),
        (legacy("houses/plains_weaponsmith_1"), 2),
        (legacy("houses/plains_temple_").numbered(3, 4), 2),
        (legacy("zombie/houses/plains_stable_1"), 2),
        (legacy("houses/plains_stable_2"), 2),
        (legacy("houses/plains_large_farm_1"), 4),
        (legacy("houses/plains_small_farm_1"), 4),
        (legacy("houses/plains_animal_pen_").numbered(1, 2), 1),
        (legacy("zombie/houses/plains_animal_pen_3"), 5),
        (legacy("zombie/houses/plains_meeting_point_4"), 3),
        (legacy("zombie/houses/plains_meeting_point_5"), 1),
        (Empty, 10),
    ]),
    pool("village/plains/zombie/streets").fallback("village/plains/terminators").terrain_matching().dir("village/plains/zombie/streets/").processors(processors::STREET_PLAINS).pieces(&[
        (legacy("corner_").padded(1, 3, 2), 2),
        (legacy("straight_").padded(1, 2, 2), 4),
        (legacy("straight_").padded(3, 4, 2), 7),
        (legacy("straight_05"), 3),
        (legacy("straight_06"), 4),
        (legacy("crossroad_01"), 2),
        (legacy("crossroad_02"), 1),
        (legacy("crossroad_").padded(3, 6, 2), 2),
        (legacy("turn_01"), 3),
    ]),
    pool("village/plains/zombie/villagers").dir("village/plains/zombie/villagers/").pieces(&[
        (legacy("nitwit"), 1),
        (legacy("unemployed"), 10),
    ]),
];
