use super::Piece::*;
use super::Pool;
use crate::keys::{placed, processors};
use mcrs_minecraft_core::rl;
use mcrs_minecraft_worldgen_feature::template::Projection::*;

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    Pool {
        name: rl!("minecraft:village/savanna/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/savanna/savanna_lamp_post_01")), 4),
            (Feature(placed::ACACIA), 4),
            (Feature(placed::PILE_HAY), 4),
            (Feature(placed::PILE_MELON), 1),
            (Empty, 4),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/houses"),
        fallback: rl!("minecraft:village/savanna/terminators"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_small_house_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_small_house_2")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_small_house_3")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_small_house_4")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_small_house_5")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_small_house_6")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_small_house_7")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_small_house_8")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_medium_house_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_medium_house_2")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_butchers_shop_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_butchers_shop_2")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_tool_smith_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_fletcher_house_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_shepherd_1")), 7),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_armorer_1")), 1),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_fisher_cottage_1")), 3),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_tannery_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_cartographer_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_library_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_mason_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_weaponsmith_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_weaponsmith_2")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_temple_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_temple_2")), 3),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_large_farm_1"), processors::FARM_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_large_farm_2"), processors::FARM_SAVANNA), 6),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_small_farm"), processors::FARM_SAVANNA), 4),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_animal_pen_1")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_animal_pen_2")), 2),
            (Legacy(rl!("minecraft:village/savanna/houses/savanna_animal_pen_3")), 2),
            (Empty, 5),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/streets"),
        fallback: rl!("minecraft:village/savanna/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/savanna/streets/corner_01"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/corner_03"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/straight_02"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/streets/straight_04"), processors::STREET_SAVANNA), 7),
            (LegacyWith(rl!("minecraft:village/savanna/streets/straight_05"), processors::STREET_SAVANNA), 3),
            (LegacyWith(rl!("minecraft:village/savanna/streets/straight_06"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/streets/straight_08"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/streets/straight_09"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/streets/straight_10"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/streets/straight_11"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/streets/crossroad_02"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/savanna/streets/crossroad_03"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/crossroad_04"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/crossroad_05"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/crossroad_06"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/crossroad_07"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/split_01"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/split_02"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/streets/turn_01"), processors::STREET_SAVANNA), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/terminators"),
        fallback: rl!("minecraft:empty"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_01"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_02"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_03"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_04"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/savanna/terminators/terminator_05"), processors::STREET_SAVANNA), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/town_centers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/savanna/town_centers/savanna_meeting_point_1")), 100),
            (Legacy(rl!("minecraft:village/savanna/town_centers/savanna_meeting_point_2")), 50),
            (Legacy(rl!("minecraft:village/savanna/town_centers/savanna_meeting_point_3")), 150),
            (Legacy(rl!("minecraft:village/savanna/town_centers/savanna_meeting_point_4")), 150),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/town_centers/savanna_meeting_point_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/town_centers/savanna_meeting_point_2"), processors::ZOMBIE_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/town_centers/savanna_meeting_point_3"), processors::ZOMBIE_SAVANNA), 3),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/town_centers/savanna_meeting_point_4"), processors::ZOMBIE_SAVANNA), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/trees"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Feature(placed::ACACIA), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/savanna/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/savanna/villagers/baby")), 1),
            (Legacy(rl!("minecraft:village/savanna/villagers/unemployed")), 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/zombie/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/savanna/savanna_lamp_post_01"), processors::ZOMBIE_SAVANNA), 4),
            (Feature(placed::ACACIA), 4),
            (Feature(placed::PILE_HAY), 4),
            (Feature(placed::PILE_MELON), 1),
            (Empty, 4),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/zombie/houses"),
        fallback: rl!("minecraft:village/savanna/zombie/terminators"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_small_house_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_small_house_2"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_small_house_3"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_small_house_4"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_small_house_5"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_small_house_6"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_small_house_7"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_small_house_8"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_medium_house_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_medium_house_2"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_butchers_shop_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_butchers_shop_2"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_tool_smith_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_fletcher_house_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_shepherd_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_armorer_1"), processors::ZOMBIE_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_fisher_cottage_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_tannery_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_cartographer_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_library_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_mason_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_weaponsmith_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_weaponsmith_2"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_temple_1"), processors::ZOMBIE_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_temple_2"), processors::ZOMBIE_SAVANNA), 3),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_large_farm_1"), processors::ZOMBIE_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_large_farm_2"), processors::ZOMBIE_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_small_farm"), processors::ZOMBIE_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/houses/savanna_animal_pen_1"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_animal_pen_2"), processors::ZOMBIE_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/houses/savanna_animal_pen_3"), processors::ZOMBIE_SAVANNA), 2),
            (Empty, 5),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/zombie/streets"),
        fallback: rl!("minecraft:village/savanna/zombie/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/corner_01"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/corner_03"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/straight_02"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/straight_04"), processors::STREET_SAVANNA), 7),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/straight_05"), processors::STREET_SAVANNA), 3),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/straight_06"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/straight_08"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/straight_09"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/straight_10"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/straight_11"), processors::STREET_SAVANNA), 4),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/crossroad_02"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/crossroad_03"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/crossroad_04"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/crossroad_05"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/crossroad_06"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/crossroad_07"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/split_01"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/split_02"), processors::STREET_SAVANNA), 2),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/streets/turn_01"), processors::STREET_SAVANNA), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/zombie/terminators"),
        fallback: rl!("minecraft:empty"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_01"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_02"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_03"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_04"), processors::STREET_SAVANNA), 1),
            (LegacyWith(rl!("minecraft:village/savanna/zombie/terminators/terminator_05"), processors::STREET_SAVANNA), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/savanna/zombie/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/savanna/zombie/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/savanna/zombie/villagers/unemployed")), 10),
        ],
    },
];
