use super::Piece::*;
use super::{Piece, Pool, legacy, pool};
use mcrs_minecraft_keys::{placed_feature, processor_list};

const STREETS: &[(Piece, i32)] = &[
    (legacy("corner_").padded(1, 3, 2), 2),
    (legacy("square_01"), 2),
    (legacy("straight_").padded(1, 3, 2), 4),
    (legacy("straight_04"), 7),
    (legacy("straight_06"), 4),
    (legacy("straight_08"), 4),
    (legacy("crossroad_02"), 1),
    (legacy("crossroad_").padded(3, 6, 2), 2),
    (legacy("turn_01"), 3),
];

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    pool("village/snowy/decor").dir("village/snowy/").pieces(&[
        (legacy("snowy_lamp_post_").padded(1, 2, 2), 4),
        (legacy("snowy_lamp_post_03"), 1),
        (Feature(placed_feature::SPRUCE), 4),
        (Feature(placed_feature::PILE_SNOW), 4),
        (Feature(placed_feature::PILE_ICE), 1),
        (Empty, 9),
    ]),
    pool("village/snowy/houses").fallback("village/snowy/terminators").dir("village/snowy/houses/").pieces(&[
        (legacy("snowy_small_house_").numbered(1, 3), 2),
        (legacy("snowy_small_house_4"), 3),
        (legacy("snowy_small_house_").numbered(5, 8), 2),
        (legacy("snowy_medium_house_").numbered(1, 3), 2),
        (legacy("snowy_butchers_shop_").numbered(1, 2), 2),
        (legacy("snowy_tool_smith_1"), 2),
        (legacy("snowy_fletcher_house_1"), 2),
        (legacy("snowy_shepherds_house_1"), 3),
        (legacy("snowy_armorer_house_").numbered(1, 2), 1),
        (legacy("snowy_fisher_cottage"), 2),
        (legacy("snowy_tannery_1"), 2),
        (legacy("snowy_cartographer_house_1"), 2),
        (legacy("snowy_library_1"), 2),
        (legacy("snowy_masons_house_").numbered(1, 2), 2),
        (legacy("snowy_weapon_smith_1"), 2),
        (legacy("snowy_temple_1"), 2),
        (legacy("snowy_farm_").numbered(1, 2).with(processor_list::FARM_SNOWY), 3),
        (legacy("snowy_animal_pen_").numbered(1, 2), 2),
        (Empty, 6),
    ]),
    pool("village/snowy/streets").fallback("village/snowy/terminators").terrain_matching().dir("village/snowy/streets/").processors(processor_list::STREET_SNOWY_OR_TAIGA).pieces(STREETS),
    pool("village/snowy/terminators").terrain_matching().dir("village/plains/terminators/").processors(processor_list::STREET_SNOWY_OR_TAIGA).pieces(&[(legacy("terminator_").padded(1, 4, 2), 1)]),
    pool("village/snowy/town_centers").dir("village/snowy/").pieces(&[
        (legacy("town_centers/snowy_meeting_point_1"), 100),
        (legacy("town_centers/snowy_meeting_point_2"), 50),
        (legacy("town_centers/snowy_meeting_point_3"), 150),
        (legacy("zombie/town_centers/snowy_meeting_point_1"), 2),
        (legacy("zombie/town_centers/snowy_meeting_point_2"), 1),
        (legacy("zombie/town_centers/snowy_meeting_point_3"), 3),
    ]),
    pool("village/snowy/trees").pieces(&[(Feature(placed_feature::SPRUCE), 1)]),
    pool("village/snowy/villagers").dir("village/snowy/villagers/").pieces(&[
        (legacy("nitwit"), 1),
        (legacy("baby"), 1),
        (legacy("unemployed"), 10),
    ]),
    pool("village/snowy/zombie/decor").dir("village/snowy/").processors(processor_list::ZOMBIE_SNOWY).pieces(&[
        (legacy("snowy_lamp_post_").padded(1, 3, 2), 1),
        (Feature(placed_feature::SPRUCE), 4),
        (Feature(placed_feature::PILE_SNOW), 4),
        (Feature(placed_feature::PILE_ICE), 4),
        (Empty, 7),
    ]),
    pool("village/snowy/zombie/houses").fallback("village/snowy/terminators").dir("village/snowy/").processors(processor_list::ZOMBIE_SNOWY).pieces(&[
        (legacy("zombie/houses/snowy_small_house_").numbered(1, 8), 2),
        (legacy("zombie/houses/snowy_medium_house_").numbered(1, 2), 2),
        (legacy("zombie/houses/snowy_medium_house_3"), 1),
        (legacy("houses/snowy_butchers_shop_").numbered(1, 2), 2),
        (legacy("houses/snowy_tool_smith_1"), 2),
        (legacy("houses/snowy_fletcher_house_1"), 2),
        (legacy("houses/snowy_shepherds_house_1"), 2),
        (legacy("houses/snowy_armorer_house_").numbered(1, 2), 1),
        (legacy("houses/snowy_fisher_cottage"), 2),
        (legacy("houses/snowy_tannery_1"), 2),
        (legacy("houses/snowy_cartographer_house_1"), 2),
        (legacy("houses/snowy_library_1"), 2),
        (legacy("houses/snowy_masons_house_").numbered(1, 2), 2),
        (legacy("houses/snowy_weapon_smith_1"), 2),
        (legacy("houses/snowy_temple_1"), 2),
        (legacy("houses/snowy_farm_").numbered(1, 2), 3),
        (legacy("houses/snowy_animal_pen_").numbered(1, 2), 2),
        (Empty, 6),
    ]),
    pool("village/snowy/zombie/streets").fallback("village/snowy/terminators").terrain_matching().dir("village/snowy/zombie/streets/").processors(processor_list::STREET_SNOWY_OR_TAIGA).pieces(STREETS),
    pool("village/snowy/zombie/villagers").dir("village/snowy/zombie/villagers/").pieces(&[
        (legacy("nitwit"), 1),
        (legacy("unemployed"), 10),
    ]),
];
