use super::Piece::*;
use super::Pool;
use crate::keys::{placed, processors};
use mcrs_minecraft_core::rl;
use mcrs_minecraft_worldgen_feature::template::Projection::*;

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    Pool {
        name: rl!("minecraft:village/taiga/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/taiga/taiga_lamp_post_1")), 10),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_1")), 4),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_2")), 1),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_3")), 1),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_4")), 1),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_5")), 2),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_6")), 1),
            (Feature(placed::SPRUCE), 4),
            (Feature(placed::PINE), 4),
            (Feature(placed::PILE_PUMPKIN), 2),
            (Feature(placed::PATCH_TAIGA_GRASS), 4),
            (Feature(placed::PATCH_BERRY_BUSH), 1),
            (Empty, 4),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/houses"),
        fallback: rl!("minecraft:village/taiga/terminators"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_small_house_1"), processors::MOSSIFY_10_PERCENT), 4),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_small_house_2"), processors::MOSSIFY_10_PERCENT), 4),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_small_house_3"), processors::MOSSIFY_10_PERCENT), 4),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_small_house_4"), processors::MOSSIFY_10_PERCENT), 4),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_small_house_5"), processors::MOSSIFY_10_PERCENT), 4),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_medium_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_medium_house_2"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_medium_house_3"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_medium_house_4"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_butcher_shop_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_tool_smith_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_fletcher_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_shepherds_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_armorer_house_1"), processors::MOSSIFY_10_PERCENT), 1),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_armorer_2"), processors::MOSSIFY_10_PERCENT), 1),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_fisher_cottage_1"), processors::MOSSIFY_10_PERCENT), 3),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_tannery_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_cartographer_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_library_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_masons_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_weaponsmith_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_weaponsmith_2"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_temple_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_large_farm_1"), processors::FARM_TAIGA), 6),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_large_farm_2"), processors::FARM_TAIGA), 6),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_small_farm_1"), processors::MOSSIFY_10_PERCENT), 1),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_animal_pen_1"), processors::MOSSIFY_10_PERCENT), 2),
            (Empty, 6),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/streets"),
        fallback: rl!("minecraft:village/taiga/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/taiga/streets/corner_01"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/streets/corner_02"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/streets/corner_03"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/streets/straight_01"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/streets/straight_02"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/streets/straight_03"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/streets/straight_04"), processors::STREET_SNOWY_OR_TAIGA), 7),
            (LegacyWith(rl!("minecraft:village/taiga/streets/straight_05"), processors::STREET_SNOWY_OR_TAIGA), 7),
            (LegacyWith(rl!("minecraft:village/taiga/streets/straight_06"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/streets/crossroad_01"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/taiga/streets/crossroad_02"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/taiga/streets/crossroad_03"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/streets/crossroad_04"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/streets/crossroad_05"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/streets/crossroad_06"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/streets/turn_01"), processors::STREET_SNOWY_OR_TAIGA), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/terminators"),
        fallback: rl!("minecraft:empty"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_01"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_02"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_03"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_04"), processors::STREET_SNOWY_OR_TAIGA), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/town_centers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/taiga/town_centers/taiga_meeting_point_1"), processors::MOSSIFY_10_PERCENT), 49),
            (LegacyWith(rl!("minecraft:village/taiga/town_centers/taiga_meeting_point_2"), processors::MOSSIFY_10_PERCENT), 49),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/town_centers/taiga_meeting_point_1"), processors::ZOMBIE_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/town_centers/taiga_meeting_point_2"), processors::ZOMBIE_TAIGA), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/taiga/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/taiga/villagers/baby")), 1),
            (Legacy(rl!("minecraft:village/taiga/villagers/unemployed")), 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/zombie/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_1")), 4),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_2")), 1),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_3")), 1),
            (Legacy(rl!("minecraft:village/taiga/taiga_decoration_4")), 1),
            (Feature(placed::SPRUCE), 4),
            (Feature(placed::PINE), 4),
            (Feature(placed::PILE_PUMPKIN), 2),
            (Feature(placed::PATCH_TAIGA_GRASS), 4),
            (Feature(placed::PATCH_BERRY_BUSH), 1),
            (Empty, 4),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/zombie/houses"),
        fallback: rl!("minecraft:village/taiga/terminators"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_small_house_1"), processors::ZOMBIE_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_small_house_2"), processors::ZOMBIE_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_small_house_3"), processors::ZOMBIE_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_small_house_4"), processors::ZOMBIE_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_small_house_5"), processors::ZOMBIE_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_medium_house_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_medium_house_2"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_medium_house_3"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_medium_house_4"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_butcher_shop_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_tool_smith_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_fletcher_house_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_shepherds_house_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_armorer_house_1"), processors::ZOMBIE_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_fisher_cottage_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_tannery_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_cartographer_house_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_library_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_masons_house_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_weaponsmith_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_weaponsmith_2"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_temple_1"), processors::ZOMBIE_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_large_farm_1"), processors::ZOMBIE_TAIGA), 6),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/houses/taiga_large_farm_2"), processors::ZOMBIE_TAIGA), 6),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_small_farm_1"), processors::ZOMBIE_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/taiga/houses/taiga_animal_pen_1"), processors::ZOMBIE_TAIGA), 2),
            (Empty, 6),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/zombie/streets"),
        fallback: rl!("minecraft:village/taiga/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/corner_01"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/corner_02"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/corner_03"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/straight_01"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/straight_02"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/straight_03"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/straight_04"), processors::STREET_SNOWY_OR_TAIGA), 7),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/straight_05"), processors::STREET_SNOWY_OR_TAIGA), 7),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/straight_06"), processors::STREET_SNOWY_OR_TAIGA), 4),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/crossroad_01"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/crossroad_02"), processors::STREET_SNOWY_OR_TAIGA), 1),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/crossroad_03"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/crossroad_04"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/crossroad_05"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/crossroad_06"), processors::STREET_SNOWY_OR_TAIGA), 2),
            (LegacyWith(rl!("minecraft:village/taiga/zombie/streets/turn_01"), processors::STREET_SNOWY_OR_TAIGA), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/taiga/zombie/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/taiga/zombie/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/taiga/zombie/villagers/unemployed")), 10),
        ],
    },
];
