use super::Piece::*;
use super::Pool;
use crate::keys::{placed, processors};
use mcrs_minecraft_core::rl;
use mcrs_minecraft_worldgen_feature::template::Projection::*;

#[rustfmt::skip]
pub const POOLS: &[Pool] = &[
    Pool {
        name: rl!("minecraft:village/plains/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/plains/plains_lamp_1")), 2),
            (Feature(placed::OAK), 1),
            (Feature(placed::FLOWER_PLAIN), 1),
            (Feature(placed::PILE_HAY), 1),
            (Empty, 2),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/houses"),
        fallback: rl!("minecraft:village/plains/terminators"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_house_2"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_house_3"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_house_4"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_house_5"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_house_6"), processors::MOSSIFY_10_PERCENT), 1),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_house_7"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_house_8"), processors::MOSSIFY_10_PERCENT), 3),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_medium_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_medium_house_2"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_big_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_butcher_shop_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_butcher_shop_2"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_tool_smith_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_fletcher_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (Legacy(rl!("minecraft:village/plains/houses/plains_shepherds_house_1")), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_armorer_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_fisher_cottage_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_tannery_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_cartographer_1"), processors::MOSSIFY_10_PERCENT), 1),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_library_1"), processors::MOSSIFY_10_PERCENT), 5),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_library_2"), processors::MOSSIFY_10_PERCENT), 1),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_masons_house_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_weaponsmith_1"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_temple_3"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_temple_4"), processors::MOSSIFY_10_PERCENT), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_stable_1"), processors::MOSSIFY_10_PERCENT), 2),
            (Legacy(rl!("minecraft:village/plains/houses/plains_stable_2")), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_large_farm_1"), processors::FARM_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_farm_1"), processors::FARM_PLAINS), 4),
            (Legacy(rl!("minecraft:village/plains/houses/plains_animal_pen_1")), 1),
            (Legacy(rl!("minecraft:village/plains/houses/plains_animal_pen_2")), 1),
            (Legacy(rl!("minecraft:village/plains/houses/plains_animal_pen_3")), 5),
            (Legacy(rl!("minecraft:village/plains/houses/plains_accessory_1")), 1),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_meeting_point_4"), processors::MOSSIFY_70_PERCENT), 3),
            (Legacy(rl!("minecraft:village/plains/houses/plains_meeting_point_5")), 1),
            (Empty, 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/streets"),
        fallback: rl!("minecraft:village/plains/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/streets/corner_01"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/streets/corner_02"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/streets/corner_03"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/streets/straight_01"), processors::STREET_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/streets/straight_02"), processors::STREET_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/streets/straight_03"), processors::STREET_PLAINS), 7),
            (LegacyWith(rl!("minecraft:village/plains/streets/straight_04"), processors::STREET_PLAINS), 7),
            (LegacyWith(rl!("minecraft:village/plains/streets/straight_05"), processors::STREET_PLAINS), 3),
            (LegacyWith(rl!("minecraft:village/plains/streets/straight_06"), processors::STREET_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/streets/crossroad_01"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/streets/crossroad_02"), processors::STREET_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/streets/crossroad_03"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/streets/crossroad_04"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/streets/crossroad_05"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/streets/crossroad_06"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/streets/turn_01"), processors::STREET_PLAINS), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/terminators"),
        fallback: rl!("minecraft:empty"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_01"), processors::STREET_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_02"), processors::STREET_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_03"), processors::STREET_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/terminators/terminator_04"), processors::STREET_PLAINS), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/town_centers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/town_centers/plains_fountain_01"), processors::MOSSIFY_20_PERCENT), 50),
            (LegacyWith(rl!("minecraft:village/plains/town_centers/plains_meeting_point_1"), processors::MOSSIFY_20_PERCENT), 50),
            (Legacy(rl!("minecraft:village/plains/town_centers/plains_meeting_point_2")), 50),
            (LegacyWith(rl!("minecraft:village/plains/town_centers/plains_meeting_point_3"), processors::MOSSIFY_70_PERCENT), 50),
            (LegacyWith(rl!("minecraft:village/plains/zombie/town_centers/plains_fountain_01"), processors::ZOMBIE_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/zombie/town_centers/plains_meeting_point_1"), processors::ZOMBIE_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/zombie/town_centers/plains_meeting_point_2"), processors::ZOMBIE_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/zombie/town_centers/plains_meeting_point_3"), processors::ZOMBIE_PLAINS), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/trees"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Feature(placed::OAK), 1),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/plains/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/plains/villagers/baby")), 1),
            (Legacy(rl!("minecraft:village/plains/villagers/unemployed")), 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/zombie/decor"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/plains_lamp_1"), processors::ZOMBIE_PLAINS), 1),
            (Feature(placed::OAK), 1),
            (Feature(placed::FLOWER_PLAIN), 1),
            (Feature(placed::PILE_HAY), 1),
            (Empty, 2),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/zombie/houses"),
        fallback: rl!("minecraft:village/plains/terminators"),
        projection: Rigid,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_small_house_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_small_house_2"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_small_house_3"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_small_house_4"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_small_house_5"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_small_house_6"), processors::ZOMBIE_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_small_house_7"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_small_house_8"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_medium_house_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_medium_house_2"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_big_house_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_butcher_shop_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_butcher_shop_2"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_tool_smith_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_fletcher_house_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_shepherds_house_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_armorer_house_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_fisher_cottage_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_tannery_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_cartographer_1"), processors::ZOMBIE_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_library_1"), processors::ZOMBIE_PLAINS), 3),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_library_2"), processors::ZOMBIE_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_masons_house_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_weaponsmith_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_temple_3"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_temple_4"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_stable_1"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_stable_2"), processors::ZOMBIE_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_large_farm_1"), processors::ZOMBIE_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_small_farm_1"), processors::ZOMBIE_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_animal_pen_1"), processors::ZOMBIE_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/houses/plains_animal_pen_2"), processors::ZOMBIE_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_animal_pen_3"), processors::ZOMBIE_PLAINS), 5),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_meeting_point_4"), processors::ZOMBIE_PLAINS), 3),
            (LegacyWith(rl!("minecraft:village/plains/zombie/houses/plains_meeting_point_5"), processors::ZOMBIE_PLAINS), 1),
            (Empty, 10),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/zombie/streets"),
        fallback: rl!("minecraft:village/plains/terminators"),
        projection: TerrainMatching,
        pieces: &[
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/corner_01"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/corner_02"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/corner_03"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/straight_01"), processors::STREET_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/straight_02"), processors::STREET_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/straight_03"), processors::STREET_PLAINS), 7),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/straight_04"), processors::STREET_PLAINS), 7),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/straight_05"), processors::STREET_PLAINS), 3),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/straight_06"), processors::STREET_PLAINS), 4),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/crossroad_01"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/crossroad_02"), processors::STREET_PLAINS), 1),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/crossroad_03"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/crossroad_04"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/crossroad_05"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/crossroad_06"), processors::STREET_PLAINS), 2),
            (LegacyWith(rl!("minecraft:village/plains/zombie/streets/turn_01"), processors::STREET_PLAINS), 3),
        ],
    },
    Pool {
        name: rl!("minecraft:village/plains/zombie/villagers"),
        fallback: rl!("minecraft:empty"),
        projection: Rigid,
        pieces: &[
            (Legacy(rl!("minecraft:village/plains/zombie/villagers/nitwit")), 1),
            (Legacy(rl!("minecraft:village/plains/zombie/villagers/unemployed")), 10),
        ],
    },
];
