// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_registry! {
    pub enum LootFunctionType;
    SetCount = "minecraft:set_count",
    SetItem = "minecraft:set_item",
    EnchantWithLevels = "minecraft:enchant_with_levels",
    EnchantRandomly = "minecraft:enchant_randomly",
    SetEnchantments = "minecraft:set_enchantments",
    SetCustomData = "minecraft:set_custom_data",
    SetComponents = "minecraft:set_components",
    FurnaceSmelt = "minecraft:furnace_smelt",
    EnchantedCountIncrease = "minecraft:enchanted_count_increase",
    SetDamage = "minecraft:set_damage",
    SetAttributes = "minecraft:set_attributes",
    SetName = "minecraft:set_name",
    ExplorationMap = "minecraft:exploration_map",
    SetStewEffect = "minecraft:set_stew_effect",
    CopyName = "minecraft:copy_name",
    SetContents = "minecraft:set_contents",
    ModifyContents = "minecraft:modify_contents",
    Filtered = "minecraft:filtered",
    LimitCount = "minecraft:limit_count",
    ApplyBonus = "minecraft:apply_bonus",
    SetLootTable = "minecraft:set_loot_table",
    ExplosionDecay = "minecraft:explosion_decay",
    SetLore = "minecraft:set_lore",
    FillPlayerHead = "minecraft:fill_player_head",
    CopyCustomData = "minecraft:copy_custom_data",
    CopyState = "minecraft:copy_state",
    SetBannerPattern = "minecraft:set_banner_pattern",
    SetPotion = "minecraft:set_potion",
    SetRandomDyes = "minecraft:set_random_dyes",
    SetRandomPotion = "minecraft:set_random_potion",
    SetInstrument = "minecraft:set_instrument",
    Sequence = "minecraft:sequence",
    CopyComponents = "minecraft:copy_components",
    SetFireworks = "minecraft:set_fireworks",
    SetFireworkExplosion = "minecraft:set_firework_explosion",
    SetBookCover = "minecraft:set_book_cover",
    SetWrittenBookPages = "minecraft:set_written_book_pages",
    SetWritableBookPages = "minecraft:set_writable_book_pages",
    ToggleTooltips = "minecraft:toggle_tooltips",
    SetOminousBottleAmplifier = "minecraft:set_ominous_bottle_amplifier",
    SetCustomModelData = "minecraft:set_custom_model_data",
    Discard = "minecraft:discard",
}
