// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_registry! {
    pub enum Attribute;
    AirDragModifier = "minecraft:air_drag_modifier",
    Armor = "minecraft:armor",
    ArmorToughness = "minecraft:armor_toughness",
    AttackDamage = "minecraft:attack_damage",
    AttackKnockback = "minecraft:attack_knockback",
    AttackSpeed = "minecraft:attack_speed",
    BelowNameDistance = "minecraft:below_name_distance",
    BlockBreakSpeed = "minecraft:block_break_speed",
    BlockInteractionRange = "minecraft:block_interaction_range",
    Bounciness = "minecraft:bounciness",
    BurningTime = "minecraft:burning_time",
    CameraDistance = "minecraft:camera_distance",
    ExplosionKnockbackResistance = "minecraft:explosion_knockback_resistance",
    EntityInteractionRange = "minecraft:entity_interaction_range",
    FallDamageMultiplier = "minecraft:fall_damage_multiplier",
    FlyingSpeed = "minecraft:flying_speed",
    FollowRange = "minecraft:follow_range",
    FrictionModifier = "minecraft:friction_modifier",
    Gravity = "minecraft:gravity",
    JumpStrength = "minecraft:jump_strength",
    KnockbackResistance = "minecraft:knockback_resistance",
    Luck = "minecraft:luck",
    MaxAbsorption = "minecraft:max_absorption",
    MaxHealth = "minecraft:max_health",
    MiningEfficiency = "minecraft:mining_efficiency",
    MovementEfficiency = "minecraft:movement_efficiency",
    MovementSpeed = "minecraft:movement_speed",
    NameTagDistance = "minecraft:name_tag_distance",
    OxygenBonus = "minecraft:oxygen_bonus",
    SafeFallDistance = "minecraft:safe_fall_distance",
    Scale = "minecraft:scale",
    SneakingSpeed = "minecraft:sneaking_speed",
    SpawnReinforcements = "minecraft:spawn_reinforcements",
    StepHeight = "minecraft:step_height",
    SubmergedMiningSpeed = "minecraft:submerged_mining_speed",
    SweepingDamageRatio = "minecraft:sweeping_damage_ratio",
    TemptRange = "minecraft:tempt_range",
    WaterMovementEfficiency = "minecraft:water_movement_efficiency",
    WaypointTransmitRange = "minecraft:waypoint_transmit_range",
    WaypointReceiveRange = "minecraft:waypoint_receive_range",
}
