[package]
name = "mcrs_minecraft_light"
description = "mcrs_minecraft_light"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_core.workspace = true
mcrs_minecraft_chunk.workspace = true
bevy_ecs = { workspace = true, optional = true }
bevy_app = { workspace = true, optional = true }
bevy_tasks = { workspace = true, features = ["multi_threaded"], optional = true }
rayon.workspace = true
rustc-hash.workspace = true

[features]
default = ["bevy"]
bevy = ["dep:bevy_ecs", "dep:bevy_app", "dep:bevy_tasks"]

[dev-dependencies]
bevy_math.workspace = true

[[test]]
name = "plugin"
required-features = ["bevy"]

[[example]]
name = "bulk_load"
required-features = ["bevy"]
