[package]
name = "mcrs_minecraft_light"
description = "mcrs_minecraft_light"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_block.workspace = true
mcrs_minecraft_core.workspace = true
mcrs_minecraft_registry.workspace = true
mcrs_minecraft_chunk.workspace = true
bevy_ecs = { workspace = true, optional = true }
bevy_app = { workspace = true, optional = true }
bevy_tasks = { workspace = true, features = ["multi_threaded"], optional = true }
rayon.workspace = true
rustc-hash.workspace = true
tracing.workspace = true

[features]
default = ["bevy"]
bevy = ["dep:bevy_ecs", "dep:bevy_app", "dep:bevy_tasks"]

[dev-dependencies]
bevy_app.workspace = true
bevy_asset.workspace = true
mcrs_minecraft_block = { workspace = true, features = ["bevy"] }
mcrs_minecraft_keys.workspace = true
mcrs_minecraft_registry = { workspace = true, features = ["test-support"] }
bevy_math.workspace = true
mcrs_minecraft_core = { workspace = true, features = ["bevy"] }

[[example]]
name = "bulk_load"
required-features = ["bevy"]
