[package]
name = "mcrs_minecraft_item"
description = "Items, item components, enchantments and armour trims"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
bevy_app.workspace = true
bevy_asset.workspace = true
bevy_ecs.workspace = true
bevy_reflect.workspace = true
bevy_tasks.workspace = true
mcrs_minecraft_assets.workspace = true
mcrs_minecraft_block.workspace = true
mcrs_minecraft_core = { workspace = true, features = ["bevy"] }
mcrs_minecraft_item_component = { workspace = true, features = ["bevy"] }
mcrs_minecraft_protocol.workspace = true
mcrs_minecraft_registry = { workspace = true, features = ["bevy"] }
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
