[package]
name = "mcrs_client"
description = "Minecraft client: window, asset corpus and environment registries"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { version = "0.19.1", default-features = false, features = [
    "std",
    "async_executor",
    "bevy_asset",
    "file_watcher",
    "bevy_log",
    "bevy_state",
    "bevy_window",
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "keyboard",
    "mouse",
    "png",
] }
bytemuck = { version = "1", features = ["derive"] }
bitflags = "2"
serde_json.workspace = true
mcrs_core.workspace = true
mcrs_engine.workspace = true
mcrs_vanilla.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
