// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::Activity;
    CORE = "minecraft:core",
    IDLE = "minecraft:idle",
    WORK = "minecraft:work",
    PLAY = "minecraft:play",
    REST = "minecraft:rest",
    MEET = "minecraft:meet",
    PANIC = "minecraft:panic",
    RAID = "minecraft:raid",
    PRE_RAID = "minecraft:pre_raid",
    HIDE = "minecraft:hide",
    FIGHT = "minecraft:fight",
    CELEBRATE = "minecraft:celebrate",
    ADMIRE_ITEM = "minecraft:admire_item",
    AVOID = "minecraft:avoid",
    RIDE = "minecraft:ride",
    PLAY_DEAD = "minecraft:play_dead",
    LONG_JUMP = "minecraft:long_jump",
    RAM = "minecraft:ram",
    TONGUE = "minecraft:tongue",
    SWIM = "minecraft:swim",
    LAY_SPAWN = "minecraft:lay_spawn",
    SNIFF = "minecraft:sniff",
    INVESTIGATE = "minecraft:investigate",
    ROAR = "minecraft:roar",
    EMERGE = "minecraft:emerge",
    DIG = "minecraft:dig",
}
