// Written by `cargo run -p mcrs_minecraft_update -- names`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::Attribute;
    AIR_DRAG_MODIFIER = "minecraft:air_drag_modifier",
    ARMOR = "minecraft:armor",
    ARMOR_TOUGHNESS = "minecraft:armor_toughness",
    ATTACK_DAMAGE = "minecraft:attack_damage",
    ATTACK_KNOCKBACK = "minecraft:attack_knockback",
    ATTACK_SPEED = "minecraft:attack_speed",
    BELOW_NAME_DISTANCE = "minecraft:below_name_distance",
    BLOCK_BREAK_SPEED = "minecraft:block_break_speed",
    BLOCK_INTERACTION_RANGE = "minecraft:block_interaction_range",
    BOUNCINESS = "minecraft:bounciness",
    BURNING_TIME = "minecraft:burning_time",
    CAMERA_DISTANCE = "minecraft:camera_distance",
    EXPLOSION_KNOCKBACK_RESISTANCE = "minecraft:explosion_knockback_resistance",
    ENTITY_INTERACTION_RANGE = "minecraft:entity_interaction_range",
    FALL_DAMAGE_MULTIPLIER = "minecraft:fall_damage_multiplier",
    FLYING_SPEED = "minecraft:flying_speed",
    FOLLOW_RANGE = "minecraft:follow_range",
    FRICTION_MODIFIER = "minecraft:friction_modifier",
    GRAVITY = "minecraft:gravity",
    JUMP_STRENGTH = "minecraft:jump_strength",
    KNOCKBACK_RESISTANCE = "minecraft:knockback_resistance",
    LUCK = "minecraft:luck",
    MAX_ABSORPTION = "minecraft:max_absorption",
    MAX_HEALTH = "minecraft:max_health",
    MINING_EFFICIENCY = "minecraft:mining_efficiency",
    MOVEMENT_EFFICIENCY = "minecraft:movement_efficiency",
    MOVEMENT_SPEED = "minecraft:movement_speed",
    NAME_TAG_DISTANCE = "minecraft:name_tag_distance",
    OXYGEN_BONUS = "minecraft:oxygen_bonus",
    SAFE_FALL_DISTANCE = "minecraft:safe_fall_distance",
    SCALE = "minecraft:scale",
    SNEAKING_SPEED = "minecraft:sneaking_speed",
    SPAWN_REINFORCEMENTS = "minecraft:spawn_reinforcements",
    STEP_HEIGHT = "minecraft:step_height",
    SUBMERGED_MINING_SPEED = "minecraft:submerged_mining_speed",
    SWEEPING_DAMAGE_RATIO = "minecraft:sweeping_damage_ratio",
    TEMPT_RANGE = "minecraft:tempt_range",
    WATER_MOVEMENT_EFFICIENCY = "minecraft:water_movement_efficiency",
    WAYPOINT_TRANSMIT_RANGE = "minecraft:waypoint_transmit_range",
    WAYPOINT_RECEIVE_RANGE = "minecraft:waypoint_receive_range",
}
