// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::BlockEntityType;
    FURNACE = "minecraft:furnace",
    CHEST = "minecraft:chest",
    TRAPPED_CHEST = "minecraft:trapped_chest",
    ENDER_CHEST = "minecraft:ender_chest",
    JUKEBOX = "minecraft:jukebox",
    DISPENSER = "minecraft:dispenser",
    DROPPER = "minecraft:dropper",
    SIGN = "minecraft:sign",
    HANGING_SIGN = "minecraft:hanging_sign",
    MOB_SPAWNER = "minecraft:mob_spawner",
    CREAKING_HEART = "minecraft:creaking_heart",
    PISTON = "minecraft:piston",
    BREWING_STAND = "minecraft:brewing_stand",
    ENCHANTING_TABLE = "minecraft:enchanting_table",
    END_PORTAL = "minecraft:end_portal",
    BEACON = "minecraft:beacon",
    SKULL = "minecraft:skull",
    DAYLIGHT_DETECTOR = "minecraft:daylight_detector",
    HOPPER = "minecraft:hopper",
    COMPARATOR = "minecraft:comparator",
    BANNER = "minecraft:banner",
    STRUCTURE_BLOCK = "minecraft:structure_block",
    END_GATEWAY = "minecraft:end_gateway",
    COMMAND_BLOCK = "minecraft:command_block",
    SHULKER_BOX = "minecraft:shulker_box",
    CONDUIT = "minecraft:conduit",
    BARREL = "minecraft:barrel",
    SMOKER = "minecraft:smoker",
    BLAST_FURNACE = "minecraft:blast_furnace",
    LECTERN = "minecraft:lectern",
    BELL = "minecraft:bell",
    JIGSAW = "minecraft:jigsaw",
    CAMPFIRE = "minecraft:campfire",
    BEEHIVE = "minecraft:beehive",
    SCULK_SENSOR = "minecraft:sculk_sensor",
    CALIBRATED_SCULK_SENSOR = "minecraft:calibrated_sculk_sensor",
    SCULK_CATALYST = "minecraft:sculk_catalyst",
    SCULK_SHRIEKER = "minecraft:sculk_shrieker",
    CHISELED_BOOKSHELF = "minecraft:chiseled_bookshelf",
    SHELF = "minecraft:shelf",
    BRUSHABLE_BLOCK = "minecraft:brushable_block",
    DECORATED_POT = "minecraft:decorated_pot",
    CRAFTER = "minecraft:crafter",
    TRIAL_SPAWNER = "minecraft:trial_spawner",
    VAULT = "minecraft:vault",
    TEST_BLOCK = "minecraft:test_block",
    TEST_INSTANCE_BLOCK = "minecraft:test_instance_block",
    COPPER_GOLEM_STATUE = "minecraft:copper_golem_statue",
    POTENT_SULFUR = "minecraft:potent_sulfur",
}
