// Written by `cargo run -p mcrs_minecraft_update -- names`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::ContextFloatProviderType;
    ABS = "minecraft:abs",
    AVG = "minecraft:avg",
    CEIL = "minecraft:ceil",
    CONDITIONAL = "minecraft:conditional",
    CONSTANT = "minecraft:constant",
    COS = "minecraft:cos",
    SUB = "minecraft:sub",
    ENCHANTMENT_LEVEL = "minecraft:enchantment_level",
    ENVIRONMENT_ATTRIBUTE = "minecraft:environment_attribute",
    FLOOR = "minecraft:floor",
    FROM_INT = "minecraft:from_int",
    LENGTH = "minecraft:length",
    MAX = "minecraft:max",
    MIN = "minecraft:min",
    MOD = "minecraft:mod",
    NEGATE = "minecraft:negate",
    NUMBER_DISPATCHER = "minecraft:number_dispatcher",
    POW = "minecraft:pow",
    MUL = "minecraft:mul",
    DIV = "minecraft:div",
    ROUND = "minecraft:round",
    SIN = "minecraft:sin",
    SQRT = "minecraft:sqrt",
    STORAGE = "minecraft:storage",
    ADD = "minecraft:add",
    TRUNCATE = "minecraft:truncate",
    UNIFORM = "minecraft:uniform",
    WEIGHTED_LIST = "minecraft:weighted_list",
}
