// Written by `cargo run -p mcrs_minecraft_update -- names`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::ContextKeySet;
    EMPTY = "minecraft:empty",
    GENERIC = "minecraft:generic",
    CHEST = "minecraft:chest",
    COMMAND = "minecraft:command",
    COMMAND_SLOT_SOURCE = "minecraft:command_slot_source",
    COMMAND_COMPUTE_DEFAULT = "minecraft:command_compute_default",
    COMMAND_COMPUTE_POSITION = "minecraft:command_compute_position",
    COMMAND_COMPUTE_ENTITY = "minecraft:command_compute_entity",
    SELECTOR = "minecraft:selector",
    VILLAGER_TRADE = "minecraft:villager_trade",
    FISHING = "minecraft:fishing",
    ENTITY = "minecraft:entity",
    EQUIPMENT = "minecraft:equipment",
    ARCHAEOLOGY = "minecraft:archaeology",
    GIFT = "minecraft:gift",
    BARTER = "minecraft:barter",
    VAULT = "minecraft:vault",
    ADVANCEMENT_REWARD = "minecraft:advancement_reward",
    ADVANCEMENT_ENTITY = "minecraft:advancement_entity",
    ADVANCEMENT_LOCATION = "minecraft:advancement_location",
    BLOCK_USE = "minecraft:block_use",
    BLOCK = "minecraft:block",
    SHEARING = "minecraft:shearing",
    ENTITY_INTERACT = "minecraft:entity_interact",
    BLOCK_INTERACT = "minecraft:block_interact",
    CONTAINER_PROCESS = "minecraft:container_process",
    ENCHANTED_DAMAGE = "minecraft:enchanted_damage",
    ENCHANTED_ITEM = "minecraft:enchanted_item",
    ENCHANTED_LOCATION = "minecraft:enchanted_location",
    ENCHANTED_ENTITY = "minecraft:enchanted_entity",
    HIT_BLOCK = "minecraft:hit_block",
}
