// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::DensityFunctionType;
    CONSTANT = "minecraft:constant",
    BLEND_ALPHA = "minecraft:blend_alpha",
    BLEND_OFFSET = "minecraft:blend_offset",
    BEARDIFIER = "minecraft:beardifier",
    NOISE = "minecraft:noise",
    END_OUTER_ISLANDS = "minecraft:end_outer_islands",
    DISTANCE_TO_POINT = "minecraft:distance_to_point",
    GRADIENT = "minecraft:gradient",
    SHIFT_A = "minecraft:shift_a",
    SHIFT_B = "minecraft:shift_b",
    SHIFT = "minecraft:shift",
    ABS = "minecraft:abs",
    SQUARE = "minecraft:square",
    CUBE = "minecraft:cube",
    SQRT = "minecraft:sqrt",
    HALF_NEGATIVE = "minecraft:half_negative",
    QUARTER_NEGATIVE = "minecraft:quarter_negative",
    RECIPROCAL = "minecraft:reciprocal",
    NEGATE = "minecraft:negate",
    SQUEEZE = "minecraft:squeeze",
    LOG = "minecraft:log",
    SIGN = "minecraft:sign",
    FLOOR = "minecraft:floor",
    ROUND = "minecraft:round",
    CEIL = "minecraft:ceil",
    TRUNCATE = "minecraft:truncate",
    ADD = "minecraft:add",
    SUB = "minecraft:sub",
    MUL = "minecraft:mul",
    DIV = "minecraft:div",
    MIN = "minecraft:min",
    MAX = "minecraft:max",
    POW = "minecraft:pow",
    SPLINE = "minecraft:spline",
    LERP = "minecraft:lerp",
    CLAMP = "minecraft:clamp",
    RANGE_CHOICE = "minecraft:range_choice",
    INTERVAL_SELECT = "minecraft:interval_select",
    CACHE = "minecraft:cache",
    BLEND_DENSITY = "minecraft:blend_density",
    INTERPOLATED = "minecraft:interpolated",
    SLICE = "minecraft:slice",
    FIND_TOP_SURFACE = "minecraft:find_top_surface",
    OLD_BLENDED_NOISE = "minecraft:old_blended_noise",
}
