// Written by `cargo run -p mcrs_minecraft_update -- names`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::EnchantmentEffectComponentType;
    DAMAGE_PROTECTION = "minecraft:damage_protection",
    DAMAGE_IMMUNITY = "minecraft:damage_immunity",
    DAMAGE = "minecraft:damage",
    SMASH_DAMAGE_PER_FALLEN_BLOCK = "minecraft:smash_damage_per_fallen_block",
    KNOCKBACK = "minecraft:knockback",
    ARMOR_EFFECTIVENESS = "minecraft:armor_effectiveness",
    POST_ATTACK = "minecraft:post_attack",
    POST_PIERCING_ATTACK = "minecraft:post_piercing_attack",
    HIT_BLOCK = "minecraft:hit_block",
    ITEM_DAMAGE = "minecraft:item_damage",
    EQUIPMENT_DROPS = "minecraft:equipment_drops",
    LOCATION_CHANGED = "minecraft:location_changed",
    TICK = "minecraft:tick",
    AMMO_USE = "minecraft:ammo_use",
    PROJECTILE_PIERCING = "minecraft:projectile_piercing",
    PROJECTILE_SPAWNED = "minecraft:projectile_spawned",
    PROJECTILE_SPREAD = "minecraft:projectile_spread",
    PROJECTILE_COUNT = "minecraft:projectile_count",
    TRIDENT_RETURN_ACCELERATION = "minecraft:trident_return_acceleration",
    FISHING_TIME_REDUCTION = "minecraft:fishing_time_reduction",
    FISHING_LUCK_BONUS = "minecraft:fishing_luck_bonus",
    BLOCK_EXPERIENCE = "minecraft:block_experience",
    MOB_EXPERIENCE = "minecraft:mob_experience",
    REPAIR_WITH_XP = "minecraft:repair_with_xp",
    ATTRIBUTES = "minecraft:attributes",
    CROSSBOW_CHARGE_TIME = "minecraft:crossbow_charge_time",
    CROSSBOW_CHARGING_SOUNDS = "minecraft:crossbow_charging_sounds",
    TRIDENT_SOUND = "minecraft:trident_sound",
    PREVENT_EQUIPMENT_DROP = "minecraft:prevent_equipment_drop",
    PREVENT_ARMOR_CHANGE = "minecraft:prevent_armor_change",
    TRIDENT_SPIN_ATTACK_STRENGTH = "minecraft:trident_spin_attack_strength",
}
