// Written by `cargo run -p mcrs_minecraft_update -- names`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::EntitySubPredicateType;
    ENTITY_TYPE = "minecraft:entity_type",
    LOCATION = "minecraft:location",
    STEPPING_ON = "minecraft:stepping_on",
    MOVEMENT_AFFECTED_BY = "minecraft:movement_affected_by",
    DISTANCE = "minecraft:distance",
    MOVEMENT = "minecraft:movement",
    EFFECTS = "minecraft:effects",
    NBT = "minecraft:nbt",
    FLAGS = "minecraft:flags",
    EQUIPMENT = "minecraft:equipment",
    PERIODIC_TICK = "minecraft:periodic_tick",
    VEHICLE = "minecraft:vehicle",
    PASSENGER = "minecraft:passenger",
    TARGETED_ENTITY = "minecraft:targeted_entity",
    TEAM = "minecraft:team",
    SLOTS = "minecraft:slots",
    COMPONENTS = "minecraft:components",
    PREDICATES = "minecraft:predicates",
    ENTITY_TAGS = "minecraft:entity_tags",
    TYPE_SPECIFIC_LIGHTNING = "minecraft:type_specific/lightning",
    TYPE_SPECIFIC_FISHING_HOOK = "minecraft:type_specific/fishing_hook",
    TYPE_SPECIFIC_PLAYER = "minecraft:type_specific/player",
    TYPE_SPECIFIC_CUBE_MOB = "minecraft:type_specific/cube_mob",
    TYPE_SPECIFIC_RAIDER = "minecraft:type_specific/raider",
    TYPE_SPECIFIC_SHEEP = "minecraft:type_specific/sheep",
}
