// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::EnvironmentAttribute;
    VISUAL_FOG_COLOR = "minecraft:visual/fog_color",
    VISUAL_FOG_START_DISTANCE = "minecraft:visual/fog_start_distance",
    VISUAL_FOG_END_DISTANCE = "minecraft:visual/fog_end_distance",
    VISUAL_SKY_FOG_END_DISTANCE = "minecraft:visual/sky_fog_end_distance",
    VISUAL_CLOUD_FOG_END_DISTANCE = "minecraft:visual/cloud_fog_end_distance",
    VISUAL_WATER_FOG_COLOR = "minecraft:visual/water_fog_color",
    VISUAL_WATER_FOG_START_DISTANCE = "minecraft:visual/water_fog_start_distance",
    VISUAL_WATER_FOG_END_DISTANCE = "minecraft:visual/water_fog_end_distance",
    VISUAL_SKY_COLOR = "minecraft:visual/sky_color",
    VISUAL_SUNRISE_SUNSET_COLOR = "minecraft:visual/sunrise_sunset_color",
    VISUAL_CLOUD_COLOR = "minecraft:visual/cloud_color",
    VISUAL_CLOUD_HEIGHT = "minecraft:visual/cloud_height",
    VISUAL_SUN_ANGLE = "minecraft:visual/sun_angle",
    VISUAL_MOON_ANGLE = "minecraft:visual/moon_angle",
    VISUAL_STAR_ANGLE = "minecraft:visual/star_angle",
    VISUAL_MOON_PHASE = "minecraft:visual/moon_phase",
    VISUAL_STAR_BRIGHTNESS = "minecraft:visual/star_brightness",
    VISUAL_HAS_SKY_OCCLUDER = "minecraft:visual/has_sky_occluder",
    VISUAL_BLOCK_LIGHT_TINT = "minecraft:visual/block_light_tint",
    VISUAL_SKY_LIGHT_COLOR = "minecraft:visual/sky_light_color",
    VISUAL_SKY_LIGHT_FACTOR = "minecraft:visual/sky_light_factor",
    VISUAL_NIGHT_VISION_COLOR = "minecraft:visual/night_vision_color",
    VISUAL_AMBIENT_LIGHT_COLOR = "minecraft:visual/ambient_light_color",
    VISUAL_DEFAULT_DRIPSTONE_PARTICLE = "minecraft:visual/default_dripstone_particle",
    VISUAL_AMBIENT_PARTICLES = "minecraft:visual/ambient_particles",
    AUDIO_BACKGROUND_MUSIC = "minecraft:audio/background_music",
    AUDIO_MUSIC_VOLUME = "minecraft:audio/music_volume",
    AUDIO_AMBIENT_SOUNDS = "minecraft:audio/ambient_sounds",
    AUDIO_FIREFLY_BUSH_SOUNDS = "minecraft:audio/firefly_bush_sounds",
    GAMEPLAY_SKY_LIGHT_LEVEL = "minecraft:gameplay/sky_light_level",
    GAMEPLAY_CAN_START_RAID = "minecraft:gameplay/can_start_raid",
    GAMEPLAY_WATER_EVAPORATES = "minecraft:gameplay/water_evaporates",
    GAMEPLAY_BED_RULE = "minecraft:gameplay/bed_rule",
    GAMEPLAY_STRAW_BED_RULE = "minecraft:gameplay/straw_bed_rule",
    GAMEPLAY_RESPAWN_ANCHOR_WORKS = "minecraft:gameplay/respawn_anchor_works",
    GAMEPLAY_NETHER_PORTAL_SPAWNS_PIGLIN = "minecraft:gameplay/nether_portal_spawns_piglin",
    GAMEPLAY_FAST_LAVA = "minecraft:gameplay/fast_lava",
    GAMEPLAY_INCREASED_FIRE_BURNOUT = "minecraft:gameplay/increased_fire_burnout",
    GAMEPLAY_EYEBLOSSOM_OPEN = "minecraft:gameplay/eyeblossom_open",
    GAMEPLAY_TURTLE_EGG_HATCH_CHANCE = "minecraft:gameplay/turtle_egg_hatch_chance",
    GAMEPLAY_PIGLINS_ZOMBIFY = "minecraft:gameplay/piglins_zombify",
    GAMEPLAY_SNOW_GOLEM_MELTS = "minecraft:gameplay/snow_golem_melts",
    GAMEPLAY_CREAKING_ACTIVE = "minecraft:gameplay/creaking_active",
    GAMEPLAY_SURFACE_SLIME_SPAWN_CHANCE = "minecraft:gameplay/surface_slime_spawn_chance",
    GAMEPLAY_CAT_WAKING_UP_GIFT_CHANCE = "minecraft:gameplay/cat_waking_up_gift_chance",
    GAMEPLAY_BEES_STAY_IN_HIVE = "minecraft:gameplay/bees_stay_in_hive",
    GAMEPLAY_MONSTERS_BURN = "minecraft:gameplay/monsters_burn",
    GAMEPLAY_CAN_PILLAGER_PATROL_SPAWN = "minecraft:gameplay/can_pillager_patrol_spawn",
    GAMEPLAY_NATURAL_MOB_SPAWNS = "minecraft:gameplay/natural_mob_spawns",
    GAMEPLAY_CREATURE_WORLD_GEN_SPAWN_PROBABILITY = "minecraft:gameplay/creature_world_gen_spawn_probability",
    GAMEPLAY_VILLAGER_ACTIVITY = "minecraft:gameplay/villager_activity",
    GAMEPLAY_BABY_VILLAGER_ACTIVITY = "minecraft:gameplay/baby_villager_activity",
}
