// Written by `cargo run -p mcrs_minecraft_update -- names`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::LootFunctionType;
    SET_COUNT = "minecraft:set_count",
    SET_ITEM = "minecraft:set_item",
    ENCHANT_WITH_LEVELS = "minecraft:enchant_with_levels",
    ENCHANT_RANDOMLY = "minecraft:enchant_randomly",
    SET_ENCHANTMENTS = "minecraft:set_enchantments",
    SET_CUSTOM_DATA = "minecraft:set_custom_data",
    SET_COMPONENTS = "minecraft:set_components",
    FURNACE_SMELT = "minecraft:furnace_smelt",
    ENCHANTED_COUNT_INCREASE = "minecraft:enchanted_count_increase",
    SET_DAMAGE = "minecraft:set_damage",
    SET_ATTRIBUTES = "minecraft:set_attributes",
    SET_NAME = "minecraft:set_name",
    EXPLORATION_MAP = "minecraft:exploration_map",
    SET_STEW_EFFECT = "minecraft:set_stew_effect",
    COPY_NAME = "minecraft:copy_name",
    SET_CONTENTS = "minecraft:set_contents",
    MODIFY_CONTENTS = "minecraft:modify_contents",
    FILTERED = "minecraft:filtered",
    LIMIT_COUNT = "minecraft:limit_count",
    APPLY_BONUS = "minecraft:apply_bonus",
    SET_LOOT_TABLE = "minecraft:set_loot_table",
    EXPLOSION_DECAY = "minecraft:explosion_decay",
    SET_LORE = "minecraft:set_lore",
    FILL_PLAYER_HEAD = "minecraft:fill_player_head",
    COPY_CUSTOM_DATA = "minecraft:copy_custom_data",
    COPY_STATE = "minecraft:copy_state",
    SET_BANNER_PATTERN = "minecraft:set_banner_pattern",
    SET_POTION = "minecraft:set_potion",
    SET_RANDOM_DYES = "minecraft:set_random_dyes",
    SET_RANDOM_POTION = "minecraft:set_random_potion",
    SET_INSTRUMENT = "minecraft:set_instrument",
    SEQUENCE = "minecraft:sequence",
    COPY_COMPONENTS = "minecraft:copy_components",
    SET_FIREWORKS = "minecraft:set_fireworks",
    SET_FIREWORK_EXPLOSION = "minecraft:set_firework_explosion",
    SET_BOOK_COVER = "minecraft:set_book_cover",
    SET_WRITTEN_BOOK_PAGES = "minecraft:set_written_book_pages",
    SET_WRITABLE_BOOK_PAGES = "minecraft:set_writable_book_pages",
    TOGGLE_TOOLTIPS = "minecraft:toggle_tooltips",
    SET_OMINOUS_BOTTLE_AMPLIFIER = "minecraft:set_ominous_bottle_amplifier",
    SET_CUSTOM_MODEL_DATA = "minecraft:set_custom_model_data",
    DISCARD = "minecraft:discard",
}
