// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::MapDecorationType;
    PLAYER = "minecraft:player",
    FRAME = "minecraft:frame",
    RED_MARKER = "minecraft:red_marker",
    BLUE_MARKER = "minecraft:blue_marker",
    TARGET_X = "minecraft:target_x",
    TARGET_POINT = "minecraft:target_point",
    PLAYER_OFF_MAP = "minecraft:player_off_map",
    PLAYER_OFF_LIMITS = "minecraft:player_off_limits",
    MANSION = "minecraft:mansion",
    MONUMENT = "minecraft:monument",
    BANNER_WHITE = "minecraft:banner_white",
    BANNER_ORANGE = "minecraft:banner_orange",
    BANNER_MAGENTA = "minecraft:banner_magenta",
    BANNER_LIGHT_BLUE = "minecraft:banner_light_blue",
    BANNER_YELLOW = "minecraft:banner_yellow",
    BANNER_LIME = "minecraft:banner_lime",
    BANNER_PINK = "minecraft:banner_pink",
    BANNER_GRAY = "minecraft:banner_gray",
    BANNER_LIGHT_GRAY = "minecraft:banner_light_gray",
    BANNER_CYAN = "minecraft:banner_cyan",
    BANNER_PURPLE = "minecraft:banner_purple",
    BANNER_BLUE = "minecraft:banner_blue",
    BANNER_BROWN = "minecraft:banner_brown",
    BANNER_GREEN = "minecraft:banner_green",
    BANNER_RED = "minecraft:banner_red",
    BANNER_BLACK = "minecraft:banner_black",
    RED_X = "minecraft:red_x",
    VILLAGE_DESERT = "minecraft:village_desert",
    VILLAGE_PLAINS = "minecraft:village_plains",
    VILLAGE_SAVANNA = "minecraft:village_savanna",
    VILLAGE_SNOWY = "minecraft:village_snowy",
    VILLAGE_TAIGA = "minecraft:village_taiga",
    JUNGLE_TEMPLE = "minecraft:jungle_temple",
    SWAMP_HUT = "minecraft:swamp_hut",
    TRIAL_CHAMBERS = "minecraft:trial_chambers",
    ABANDONED_CAMP = "minecraft:abandoned_camp",
    ANCIENT_CITY = "minecraft:ancient_city",
    DESERT_PYRAMID = "minecraft:desert_pyramid",
    MINESHAFT = "minecraft:mineshaft",
    OCEAN_RUIN_WARM = "minecraft:ocean_ruin_warm",
}
