// Written by `cargo run -p mcrs_minecraft_update -- names`; do not edit.

mcrs_minecraft_registry::static_keys! {
    crate::Menu;
    GENERIC_9X1 = "minecraft:generic_9x1",
    GENERIC_9X2 = "minecraft:generic_9x2",
    GENERIC_9X3 = "minecraft:generic_9x3",
    GENERIC_9X4 = "minecraft:generic_9x4",
    GENERIC_9X5 = "minecraft:generic_9x5",
    GENERIC_9X6 = "minecraft:generic_9x6",
    GENERIC_3X3 = "minecraft:generic_3x3",
    CRAFTER_3X3 = "minecraft:crafter_3x3",
    ANVIL = "minecraft:anvil",
    BEACON = "minecraft:beacon",
    BLAST_FURNACE = "minecraft:blast_furnace",
    BREWING_STAND = "minecraft:brewing_stand",
    CRAFTING = "minecraft:crafting",
    ENCHANTMENT = "minecraft:enchantment",
    FURNACE = "minecraft:furnace",
    GRINDSTONE = "minecraft:grindstone",
    HOPPER = "minecraft:hopper",
    LECTERN = "minecraft:lectern",
    LOOM = "minecraft:loom",
    MERCHANT = "minecraft:merchant",
    SHULKER_BOX = "minecraft:shulker_box",
    SMITHING = "minecraft:smithing",
    SMOKER = "minecraft:smoker",
    CARTOGRAPHY_TABLE = "minecraft:cartography_table",
    STONECUTTER = "minecraft:stonecutter",
}
