[package]
name = "mcrs_minecraft_block"
description = "mcrs_minecraft_block"
version.workspace = true
edition.workspace = true

[dependencies]
mcrs_voxel_math.workspace = true
mcrs_voxel_storage.workspace = true
mcrs_voxel_world.workspace = true
mcrs_protocol.workspace = true
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_ecs_macros.workspace = true
rustc-hash.workspace = true
bitflags = "2.10.0"
tracing.workspace = true
