// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

use mcrs_minecraft_core::{ResourceKey, rl};

pub const BEDROCK_FLOOR: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:bedrock_floor"));
pub const BEDROCK_ROOF: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:bedrock_roof"));
pub const END: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:end"));
pub const NETHER: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:nether"));
pub const OVERWORLD: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld"));
pub const OVERWORLD_BIOME_SURFACE: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface"));
pub const OVERWORLD_BIOME_SURFACE_DAPPLED_FOREST: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/dappled_forest"));
pub const OVERWORLD_BIOME_SURFACE_DEFAULT: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/default"));
pub const OVERWORLD_BIOME_SURFACE_DRIPSTONE_CAVES: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/dripstone_caves"));
pub const OVERWORLD_BIOME_SURFACE_FROZEN_PEAKS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/frozen_peaks"));
pub const OVERWORLD_BIOME_SURFACE_GROVE: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/grove"));
pub const OVERWORLD_BIOME_SURFACE_ICE_SPIKES: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/ice_spikes"));
pub const OVERWORLD_BIOME_SURFACE_JAGGED_PEAKS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/jagged_peaks"));
pub const OVERWORLD_BIOME_SURFACE_MANGROVE_SWAMP: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/mangrove_swamp"));
pub const OVERWORLD_BIOME_SURFACE_MUSHROOM_FIELDS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/mushroom_fields"));
pub const OVERWORLD_BIOME_SURFACE_OLD_GROWTH_PINE_TAIGA: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/old_growth_pine_taiga"));
pub const OVERWORLD_BIOME_SURFACE_SNOWY_SLOPES: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/snowy_slopes"));
pub const OVERWORLD_BIOME_SURFACE_STONY_PEAKS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/stony_peaks"));
pub const OVERWORLD_BIOME_SURFACE_STONY_SHORE: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/stony_shore"));
pub const OVERWORLD_BIOME_SURFACE_SULFUR_CAVES: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/sulfur_caves"));
pub const OVERWORLD_BIOME_SURFACE_WINDSWEPT_GRAVELLY_HILLS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/windswept_gravelly_hills"));
pub const OVERWORLD_BIOME_SURFACE_WINDSWEPT_HILLS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/windswept_hills"));
pub const OVERWORLD_BIOME_SURFACE_WINDSWEPT_SAVANNA: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/biome_surface/windswept_savanna"));
pub const OVERWORLD_COPPER_ORE_VEIN: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/copper_ore_vein"));
pub const OVERWORLD_GRAVEL_OR_STONE_IF_CEILING: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/gravel_or_stone_if_ceiling"));
pub const OVERWORLD_IRON_ORE_VEIN: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/iron_ore_vein"));
pub const OVERWORLD_POWDER_SNOW_SURFACE: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/powder_snow_surface"));
pub const OVERWORLD_POWDER_SNOW_UNDER_SURFACE: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/powder_snow_under_surface"));
pub const OVERWORLD_SAND_OR_SANDSTONE_IF_CEILING: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/sand_or_sandstone_if_ceiling"));
pub const OVERWORLD_SULFUR_CAVE_BANDS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/sulfur_cave_bands"));
pub const OVERWORLD_SURFACE: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/surface"));
pub const OVERWORLD_UNDER_BIOME_SURFACE: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/under_biome_surface"));
pub const OVERWORLD_UNDER_BIOME_SURFACE_DEFAULT: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/under_biome_surface/default"));
pub const OVERWORLD_UNDER_BIOME_SURFACE_FROZEN_PEAKS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/under_biome_surface/frozen_peaks"));
pub const OVERWORLD_UNDER_BIOME_SURFACE_GROVE: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/under_biome_surface/grove"));
pub const OVERWORLD_UNDER_BIOME_SURFACE_JAGGED_PEAKS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/under_biome_surface/jagged_peaks"));
pub const OVERWORLD_UNDER_BIOME_SURFACE_SNOWY_SLOPES: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/under_biome_surface/snowy_slopes"));
pub const OVERWORLD_UNDER_BIOME_SURFACE_WINDSWEPT_GRAVELLY_HILLS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/under_biome_surface/windswept_gravelly_hills"));
pub const OVERWORLD_UNDER_BIOME_SURFACE_WINDSWEPT_SAVANNA: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/under_biome_surface/windswept_savanna"));
pub const OVERWORLD_UNDERGROUND: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld/underground"));
pub const OVERWORLD_CAVES: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld_caves"));
pub const OVERWORLD_FLOATING_ISLANDS: ResourceKey<crate::proto::MaterialRule, &'static str> = ResourceKey::new(rl!("minecraft:overworld_floating_islands"));
