[package]
name = "mcrs_minecraft_dimension_environment"
description = "Dimension types and the environment attribute layers of a dimension"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_value_provider.workspace = true
mcrs_minecraft_dimension.workspace = true
bevy_ecs.workspace = true
bevy_math.workspace = true
mcrs_minecraft_block.workspace = true
mcrs_minecraft_core = { workspace = true, features = ["bevy"] }
mcrs_minecraft_environment = { workspace = true, features = ["bevy"] }
mcrs_minecraft_registry = { workspace = true, features = ["bevy"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
mcrs_minecraft_worldgen_testing.workspace = true
