// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_registry! {
    pub enum ContextKeySet;
    Empty = "minecraft:empty",
    Generic = "minecraft:generic",
    Chest = "minecraft:chest",
    Command = "minecraft:command",
    CommandSlotSource = "minecraft:command_slot_source",
    CommandComputeDefault = "minecraft:command_compute_default",
    CommandComputePosition = "minecraft:command_compute_position",
    CommandComputeEntity = "minecraft:command_compute_entity",
    Selector = "minecraft:selector",
    VillagerTrade = "minecraft:villager_trade",
    Fishing = "minecraft:fishing",
    Entity = "minecraft:entity",
    Equipment = "minecraft:equipment",
    Archaeology = "minecraft:archaeology",
    Gift = "minecraft:gift",
    Barter = "minecraft:barter",
    Vault = "minecraft:vault",
    AdvancementReward = "minecraft:advancement_reward",
    AdvancementEntity = "minecraft:advancement_entity",
    AdvancementLocation = "minecraft:advancement_location",
    BlockUse = "minecraft:block_use",
    Block = "minecraft:block",
    Shearing = "minecraft:shearing",
    EntityInteract = "minecraft:entity_interact",
    BlockInteract = "minecraft:block_interact",
    ContainerProcess = "minecraft:container_process",
    EnchantedDamage = "minecraft:enchanted_damage",
    EnchantedItem = "minecraft:enchanted_item",
    EnchantedLocation = "minecraft:enchanted_location",
    EnchantedEntity = "minecraft:enchanted_entity",
    HitBlock = "minecraft:hit_block",
}
