// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_registry! {
    pub enum MapDecorationType;
    Player = "minecraft:player",
    Frame = "minecraft:frame",
    RedMarker = "minecraft:red_marker",
    BlueMarker = "minecraft:blue_marker",
    TargetX = "minecraft:target_x",
    TargetPoint = "minecraft:target_point",
    PlayerOffMap = "minecraft:player_off_map",
    PlayerOffLimits = "minecraft:player_off_limits",
    Mansion = "minecraft:mansion",
    Monument = "minecraft:monument",
    BannerWhite = "minecraft:banner_white",
    BannerOrange = "minecraft:banner_orange",
    BannerMagenta = "minecraft:banner_magenta",
    BannerLightBlue = "minecraft:banner_light_blue",
    BannerYellow = "minecraft:banner_yellow",
    BannerLime = "minecraft:banner_lime",
    BannerPink = "minecraft:banner_pink",
    BannerGray = "minecraft:banner_gray",
    BannerLightGray = "minecraft:banner_light_gray",
    BannerCyan = "minecraft:banner_cyan",
    BannerPurple = "minecraft:banner_purple",
    BannerBlue = "minecraft:banner_blue",
    BannerBrown = "minecraft:banner_brown",
    BannerGreen = "minecraft:banner_green",
    BannerRed = "minecraft:banner_red",
    BannerBlack = "minecraft:banner_black",
    RedX = "minecraft:red_x",
    VillageDesert = "minecraft:village_desert",
    VillagePlains = "minecraft:village_plains",
    VillageSavanna = "minecraft:village_savanna",
    VillageSnowy = "minecraft:village_snowy",
    VillageTaiga = "minecraft:village_taiga",
    JungleTemple = "minecraft:jungle_temple",
    SwampHut = "minecraft:swamp_hut",
    TrialChambers = "minecraft:trial_chambers",
    AbandonedCamp = "minecraft:abandoned_camp",
    AncientCity = "minecraft:ancient_city",
    DesertPyramid = "minecraft:desert_pyramid",
    Mineshaft = "minecraft:mineshaft",
    OceanRuinWarm = "minecraft:ocean_ruin_warm",
}
