// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

mcrs_minecraft_registry::static_registry! {
    pub enum MobEffect;
    Speed = "minecraft:speed",
    Slowness = "minecraft:slowness",
    Haste = "minecraft:haste",
    MiningFatigue = "minecraft:mining_fatigue",
    Strength = "minecraft:strength",
    InstantHealth = "minecraft:instant_health",
    InstantDamage = "minecraft:instant_damage",
    JumpBoost = "minecraft:jump_boost",
    Nausea = "minecraft:nausea",
    Regeneration = "minecraft:regeneration",
    Resistance = "minecraft:resistance",
    FireResistance = "minecraft:fire_resistance",
    WaterBreathing = "minecraft:water_breathing",
    Invisibility = "minecraft:invisibility",
    Blindness = "minecraft:blindness",
    NightVision = "minecraft:night_vision",
    Hunger = "minecraft:hunger",
    Weakness = "minecraft:weakness",
    Poison = "minecraft:poison",
    Wither = "minecraft:wither",
    HealthBoost = "minecraft:health_boost",
    Absorption = "minecraft:absorption",
    Saturation = "minecraft:saturation",
    Glowing = "minecraft:glowing",
    Levitation = "minecraft:levitation",
    Luck = "minecraft:luck",
    Unluck = "minecraft:unluck",
    SlowFalling = "minecraft:slow_falling",
    ConduitPower = "minecraft:conduit_power",
    DolphinsGrace = "minecraft:dolphins_grace",
    BadOmen = "minecraft:bad_omen",
    HeroOfTheVillage = "minecraft:hero_of_the_village",
    Darkness = "minecraft:darkness",
    TrialOmen = "minecraft:trial_omen",
    RaidOmen = "minecraft:raid_omen",
    WindCharged = "minecraft:wind_charged",
    Weaving = "minecraft:weaving",
    Oozing = "minecraft:oozing",
    Infested = "minecraft:infested",
    BreathOfTheNautilus = "minecraft:breath_of_the_nautilus",
}
