[package]
name = "mcrs_minecraft_chunk"
description = "mcrs_minecraft_chunk"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_core.workspace = true
rustc-hash.workspace = true
bevy_ecs = { workspace = true, optional = true }
bevy_math.workspace = true

[features]
default = ["bevy"]
bevy = ["dep:bevy_ecs"]
