[package]
name = "mcrs_minecraft_worldgen"
description = "The world generator: the worldgen registries, their loaders and the beardifier"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
bevy_app.workspace = true
bevy_asset.workspace = true
bevy_ecs.workspace = true
bevy_reflect.workspace = true
mcrs_minecraft_assets.workspace = true
bevy_math.workspace = true
mcrs_minecraft_chunk.workspace = true
mcrs_minecraft_core = { workspace = true, features = ["bevy"] }
mcrs_minecraft_nbt.workspace = true
mcrs_minecraft_worldgen_noise.workspace = true
mcrs_minecraft_worldgen_density = { workspace = true, features = ["bevy"] }
mcrs_minecraft_worldgen_surface = { workspace = true, features = ["bevy"] }
mcrs_minecraft_worldgen_feature.workspace = true
mcrs_minecraft_worldgen_carver = { workspace = true, features = ["bevy"] }
mcrs_minecraft_worldgen_structure.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
bytes.workspace = true
mcrs_minecraft_worldgen_testing.workspace = true

[features]
default = ["fast"]
fast = ["mcrs_minecraft_worldgen_noise/fast", "mcrs_minecraft_worldgen_density/fast", "mcrs_minecraft_worldgen_surface/fast", "mcrs_minecraft_worldgen_feature/fast"]
