use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Registry folders whose `.json` files should be enumerated at compile time
/// and exposed at runtime as `&[&str]` slices in the generated module.
///
/// Adding a new dynamic registry: append `(rust_const_name, "<folder under assets/>")`.
/// Adding a new file to an existing registry: drop the JSON into `assets/<folder>/`
/// — the build script will pick it up on the next rebuild.
const REGISTRY_FOLDERS: &[(&str, &str)] = &[
    ("BIOME", "minecraft/worldgen/biome"),
    ("CHAT_TYPE", "minecraft/chat_type"),
    ("DIMENSION_TYPE", "minecraft/dimension_type"),
    ("TRIM_PATTERN", "minecraft/trim_pattern"),
    ("TRIM_MATERIAL", "minecraft/trim_material"),
    ("WOLF_VARIANT", "minecraft/wolf_variant"),
    ("WOLF_SOUND_VARIANT", "minecraft/wolf_sound_variant"),
    ("PIG_SOUND_VARIANT", "minecraft/pig_sound_variant"),
    ("CAT_SOUND_VARIANT", "minecraft/cat_sound_variant"),
    ("COW_SOUND_VARIANT", "minecraft/cow_sound_variant"),
    ("CHICKEN_SOUND_VARIANT", "minecraft/chicken_sound_variant"),
    ("PIG_VARIANT", "minecraft/pig_variant"),
    ("FROG_VARIANT", "minecraft/frog_variant"),
    ("CAT_VARIANT", "minecraft/cat_variant"),
    ("COW_VARIANT", "minecraft/cow_variant"),
    ("CHICKEN_VARIANT", "minecraft/chicken_variant"),
    ("ZOMBIE_NAUTILUS_VARIANT", "minecraft/zombie_nautilus_variant"),
    ("PAINTING_VARIANT", "minecraft/painting_variant"),
    ("DAMAGE_TYPE", "minecraft/damage_type"),
    ("BANNER_PATTERN", "minecraft/banner_pattern"),
    ("JUKEBOX_SONG", "minecraft/jukebox_song"),
    ("INSTRUMENT", "minecraft/instrument"),
    ("DIALOG", "minecraft/dialog"),
    ("TIMELINE", "minecraft/timeline"),
    ("WORLD_CLOCK", "minecraft/world_clock"),
    ("TEST_ENVIRONMENT", "minecraft/test_environment"),
    ("TEST_INSTANCE", "minecraft/test_instance"),
];

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let assets_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("crate is two levels below workspace root")
        .join("assets");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", assets_root.display());

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit by hand.\n\n");

    for (const_name, folder) in REGISTRY_FOLDERS {
        let folder_abs = assets_root.join(folder);
        let mut files: Vec<String> = match fs::read_dir(&folder_abs) {
            Ok(rd) => rd
                .filter_map(Result::ok)
                .filter_map(|e| {
                    let p = e.path();
                    if p.extension().and_then(|s| s.to_str()) != Some("json") {
                        return None;
                    }
                    let name = p.file_name()?.to_str()?.to_owned();
                    Some(format!("{folder}/{name}"))
                })
                .collect(),
            Err(_) => Vec::new(),
        };
        files.sort();
        println!(
            "cargo:rerun-if-changed={}",
            folder_abs.display()
        );

        code.push_str(&format!(
            "pub const FOLDER_{const_name}: &str = \"{folder}\";\n"
        ));
        code.push_str(&format!(
            "pub const FILES_{const_name}: &[&str] = &[\n"
        ));
        for f in &files {
            code.push_str(&format!("    \"{f}\",\n"));
        }
        code.push_str("];\n\n");
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("registry_files.rs");
    fs::write(&out_file, code).expect("write registry_files.rs");
}
