[package]
name = "mcrs_minecraft_profile"
description = "Game profiles, their properties and the resolvable profile of a player head"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
mcrs_minecraft_core.workspace = true
mcrs_minecraft_nbt.workspace = true
anyhow.workspace = true
base64.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["serde"] }
