[package]
name = "mcrs_minecraft_profile"
description = "Game profiles, their properties and the resolvable profile of a player head"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[features]
bevy = ["dep:bevy_ecs"]

[dependencies]
bevy_ecs = { workspace = true, optional = true }
mcrs_minecraft_core.workspace = true
mcrs_minecraft_nbt.workspace = true
anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["serde"] }
