use std::collections::BTreeMap;
use std::path::PathBuf;

use mcrs_minecraft_protocol::BlockStateId;
use mcrs_voxel_storage::VoxelId;

use super::corpus;
use super::surface::{biome_ids, overworld_material_router, surfaced_column};

const MAGIC: &[u8; 8] = b"MCSURFC0";
/// `SharedConstants.WORLD_VERSION` of the snapshot the dumps came from, so a
/// corpus bump cannot silently invalidate them.
const WORLD_VERSION: u32 = 5015;

const DUMPS: [&str; 7] = [
    "surface_s42_c0_0.bin",
    "surface_s42_c100_100.bin",
    "surface_s2_c3_-7.bin",
    "surface_s42_c-118_-119.bin",
    "surface_s2_c19_-1.bin",
    "surface_s2_c52_36.bin",
    "surface_s2_c20_-3.bin",
];

struct Dump {
    seed: u64,
    chunk_x: i32,
    chunk_z: i32,
    min_y: i32,
    height: i32,
    palette: Vec<String>,
    cells: Vec<u32>,
}

impl Dump {
    /// The block vanilla left at this position, without its properties: no rule
    /// in the corpus tells two states of one block apart.
    fn at(&self, x: i32, y: i32, z: i32) -> &str {
        let index = ((z * 16 + x) * self.height + (y - self.min_y)) as usize;
        self.palette[self.cells[index] as usize]
            .split('[')
            .next()
            .unwrap()
    }
}

struct Reader<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn take(&mut self, n: usize) -> &'a [u8] {
        let out = &self.data[self.pos..self.pos + n];
        self.pos += n;
        out
    }
    fn u32(&mut self) -> u32 {
        u32::from_le_bytes(self.take(4).try_into().unwrap())
    }
    fn i32(&mut self) -> i32 {
        i32::from_le_bytes(self.take(4).try_into().unwrap())
    }
    fn i64(&mut self) -> i64 {
        i64::from_le_bytes(self.take(8).try_into().unwrap())
    }
    fn string(&mut self) -> String {
        let len = self.u32() as usize;
        String::from_utf8(self.take(len).to_vec()).unwrap()
    }
}

fn read_dump(name: &str) -> Dump {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("src/world/generate/tests/fixtures")
        .join(name);
    let data = std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let mut r = Reader {
        data: &data,
        pos: 0,
    };
    assert_eq!(r.take(8), MAGIC, "{name} is not a surface dump");
    assert_eq!(r.u32(), 1, "unsupported surface dump version");
    assert_eq!(
        r.u32(),
        WORLD_VERSION,
        "{name} was dumped from a different snapshot than this corpus targets"
    );
    assert_eq!(r.string(), "minecraft:overworld");
    let seed = r.i64() as u64;
    let chunk_x = r.i32();
    let chunk_z = r.i32();
    let min_y = r.i32();
    let height = r.i32();
    let palette: Vec<String> = (0..r.u32()).map(|_| r.string()).collect();
    let mut cells = Vec::with_capacity((16 * 16 * height) as usize);
    for _ in 0..r.u32() {
        let (id, run) = (r.u32(), r.u32());
        cells.extend(std::iter::repeat_n(id, run as usize));
    }
    assert_eq!(r.pos, data.len(), "trailing bytes in {name}");
    assert_eq!(cells.len(), (16 * 16 * height) as usize, "{name} is short");
    Dump {
        seed,
        chunk_x,
        chunk_z,
        min_y,
        height,
        palette,
        cells,
    }
}

fn name_of(state: VoxelId) -> &'static str {
    corpus().owner(BlockStateId(state.0)).identifier.as_str()
}

/// Block for block against seven chunks generated by 26.3 itself
/// (`tools/vanilla-oracle`, task `dumpSurface`) — the measurement S23 says this
/// stage admits.
///
/// Nothing is tolerated: every position of every dump matches, whether the
/// density left it empty or filled it with rock.
#[test]
fn a_surfaced_column_matches_the_vanilla_chunk() {
    let ids = biome_ids();
    let mut differ: BTreeMap<(String, &str), usize> = BTreeMap::new();
    let mut first: Option<String> = None;
    let mut checked = 0usize;

    for name in DUMPS {
        let dump = read_dump(name);
        let router = overworld_material_router(dump.seed, &ids);
        let y_sections: Vec<i32> = ((dump.min_y / 16)..((dump.min_y + dump.height) / 16)).collect();
        let surfaced = surfaced_column(
            &router,
            &ids,
            dump.chunk_x,
            dump.chunk_z,
            &y_sections,
            false,
        );

        for z in 0..16 {
            for x in 0..16 {
                for y in dump.min_y..dump.min_y + dump.height {
                    let want = dump.at(x, y, z);
                    let got = name_of(
                        surfaced
                            .get(x, y, z)
                            .expect("the column carries every section"),
                    );
                    checked += 1;
                    if got == want {
                        continue;
                    }
                    *differ.entry((want.to_owned(), got)).or_default() += 1;
                    first.get_or_insert_with(|| {
                        format!("{name} at {x},{y},{z}: want {want}, got {got}")
                    });
                }
            }
        }
    }

    assert_eq!(
        checked,
        DUMPS.len() * 16 * 16 * 384,
        "a dump went uncompared"
    );
    assert!(
        differ.is_empty(),
        "{} of {checked} blocks differ from vanilla: {differ:?}\nfirst {first:?}",
        differ.values().sum::<usize>()
    );
}

/// The three pieces of the stage that are not rules are only compared if a dump
/// holds them, and which chunk holds what is not visible from a file name.
#[test]
fn the_dumps_hold_the_clay_bands_a_pillar_and_an_iceberg() {
    let mut blocks: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    let mut tallest_over_median = 0;
    for name in DUMPS {
        let dump = read_dump(name);
        for state in &dump.palette {
            blocks.insert(state.split('[').next().unwrap().to_owned());
        }
        let mut tops: Vec<i32> = (0..16)
            .flat_map(|z| (0..16).map(move |x| (x, z)))
            .map(|(x, z)| {
                (dump.min_y..dump.min_y + dump.height)
                    .rev()
                    .find(|&y| dump.at(x, y, z) != "minecraft:air")
                    .unwrap_or(dump.min_y)
            })
            .collect();
        tops.sort_unstable();
        tallest_over_median = tallest_over_median.max(tops[255] - tops[128]);
    }

    for block in [
        "minecraft:orange_terracotta",
        "minecraft:white_terracotta",
        "minecraft:light_gray_terracotta",
        "minecraft:yellow_terracotta",
        "minecraft:red_terracotta",
        "minecraft:terracotta",
        "minecraft:packed_ice",
        "minecraft:gravel",
        "minecraft:grass_block",
        "minecraft:bedrock",
        "minecraft:raw_iron_block",
        "minecraft:tuff",
        "minecraft:granite",
    ] {
        assert!(
            blocks.contains(block),
            "no dump holds {block}, so nothing compares it: {blocks:?}"
        );
    }
    // A badlands pillar stands some seventeen blocks over the terrain around it;
    // without one the pillar pass would go uncompared in a chunk that surfaces
    // in terracotta anyway.
    assert!(
        tallest_over_median >= 15,
        "the tallest strip of any dump is only {tallest_over_median} over its median, so no pillar was captured"
    );
}
