// Written by `cargo run -p mcrs_minecraft_update -- keys`; do not edit.

use mcrs_minecraft_core::{StaticResourceLocation, TypeBinding};

#[rustfmt::skip]
pub const STATIC_REGISTRIES: &[(StaticResourceLocation, &[StaticResourceLocation])] = &[
    (mcrs_minecraft_keys::ACTIVITY.location(), mcrs_minecraft_keys::activity::ENTRIES),
    (mcrs_minecraft_keys::ATTRIBUTE.location(), mcrs_minecraft_keys::attribute::ENTRIES),
    (mcrs_minecraft_keys::ATTRIBUTE_TYPE.location(), mcrs_minecraft_keys::attribute_type::ENTRIES),
    (mcrs_minecraft_keys::BLOCK.location(), mcrs_minecraft_keys::block::ENTRIES),
    (mcrs_minecraft_keys::BLOCK_ENTITY_TYPE.location(), mcrs_minecraft_keys::block_entity_type::ENTRIES),
    (mcrs_minecraft_keys::BLOCK_PREDICATE_TYPE.location(), mcrs_minecraft_keys::block_predicate_type::ENTRIES),
    (mcrs_minecraft_keys::CHUNK_STATUS.location(), mcrs_minecraft_keys::chunk_status::ENTRIES),
    (mcrs_minecraft_keys::COMMAND_ARGUMENT_TYPE.location(), mcrs_minecraft_keys::command_argument_type::ENTRIES),
    (mcrs_minecraft_keys::CONSUME_EFFECT_TYPE.location(), mcrs_minecraft_keys::consume_effect_type::ENTRIES),
    (mcrs_minecraft_keys::CONTEXT_FLOAT_PROVIDER_TYPE.location(), mcrs_minecraft_keys::context_float_provider_type::ENTRIES),
    (mcrs_minecraft_keys::CONTEXT_INT_PROVIDER_TYPE.location(), mcrs_minecraft_keys::context_int_provider_type::ENTRIES),
    (mcrs_minecraft_keys::CONTEXT_KEY_SET.location(), mcrs_minecraft_keys::context_key_set::ENTRIES),
    (mcrs_minecraft_keys::CREATIVE_MODE_TAB.location(), mcrs_minecraft_keys::creative_mode_tab::ENTRIES),
    (mcrs_minecraft_keys::CUSTOM_STAT.location(), mcrs_minecraft_keys::custom_stat::ENTRIES),
    (mcrs_minecraft_keys::DATA_COMPONENT_PREDICATE_TYPE.location(), mcrs_minecraft_keys::data_component_predicate_type::ENTRIES),
    (mcrs_minecraft_keys::DATA_COMPONENT_TYPE.location(), mcrs_minecraft_keys::data_component_type::ENTRIES),
    (mcrs_minecraft_keys::DEBUG_SUBSCRIPTION.location(), mcrs_minecraft_keys::debug_subscription::ENTRIES),
    (mcrs_minecraft_keys::DIALOG_ACTION_TYPE.location(), mcrs_minecraft_keys::dialog_action_type::ENTRIES),
    (mcrs_minecraft_keys::DIALOG_BODY_TYPE.location(), mcrs_minecraft_keys::dialog_body_type::ENTRIES),
    (mcrs_minecraft_keys::DIALOG_TYPE.location(), mcrs_minecraft_keys::dialog_type::ENTRIES),
    (mcrs_minecraft_keys::ENCHANTMENT_EFFECT_COMPONENT_TYPE.location(), mcrs_minecraft_keys::enchantment_effect_component_type::ENTRIES),
    (mcrs_minecraft_keys::ENCHANTMENT_ENTITY_EFFECT_TYPE.location(), mcrs_minecraft_keys::enchantment_entity_effect_type::ENTRIES),
    (mcrs_minecraft_keys::ENCHANTMENT_LEVEL_BASED_VALUE_TYPE.location(), mcrs_minecraft_keys::enchantment_level_based_value_type::ENTRIES),
    (mcrs_minecraft_keys::ENCHANTMENT_LOCATION_BASED_EFFECT_TYPE.location(), mcrs_minecraft_keys::enchantment_location_based_effect_type::ENTRIES),
    (mcrs_minecraft_keys::ENCHANTMENT_PROVIDER_TYPE.location(), mcrs_minecraft_keys::enchantment_provider_type::ENTRIES),
    (mcrs_minecraft_keys::ENCHANTMENT_VALUE_EFFECT_TYPE.location(), mcrs_minecraft_keys::enchantment_value_effect_type::ENTRIES),
    (mcrs_minecraft_keys::ENTITY_SUB_PREDICATE_TYPE.location(), mcrs_minecraft_keys::entity_sub_predicate_type::ENTRIES),
    (mcrs_minecraft_keys::ENTITY_TYPE.location(), mcrs_minecraft_keys::entity_type::ENTRIES),
    (mcrs_minecraft_keys::ENVIRONMENT_ATTRIBUTE.location(), mcrs_minecraft_keys::environment_attribute::ENTRIES),
    (mcrs_minecraft_keys::FLOAT_PROVIDER_TYPE.location(), mcrs_minecraft_keys::float_provider_type::ENTRIES),
    (mcrs_minecraft_keys::FLUID.location(), mcrs_minecraft_keys::fluid::ENTRIES),
    (mcrs_minecraft_keys::GAME_EVENT.location(), mcrs_minecraft_keys::game_event::ENTRIES),
    (mcrs_minecraft_keys::GAME_RULE.location(), mcrs_minecraft_keys::game_rule::ENTRIES),
    (mcrs_minecraft_keys::HEIGHT_PROVIDER_TYPE.location(), mcrs_minecraft_keys::height_provider_type::ENTRIES),
    (mcrs_minecraft_keys::INCOMING_RPC_METHODS.location(), mcrs_minecraft_keys::incoming_rpc_methods::ENTRIES),
    (mcrs_minecraft_keys::INPUT_CONTROL_TYPE.location(), mcrs_minecraft_keys::input_control_type::ENTRIES),
    (mcrs_minecraft_keys::INT_PROVIDER_TYPE.location(), mcrs_minecraft_keys::int_provider_type::ENTRIES),
    (mcrs_minecraft_keys::ITEM.location(), mcrs_minecraft_keys::item::ENTRIES),
    (mcrs_minecraft_keys::LOOT_CONDITION_TYPE.location(), mcrs_minecraft_keys::loot_condition_type::ENTRIES),
    (mcrs_minecraft_keys::LOOT_FUNCTION_TYPE.location(), mcrs_minecraft_keys::loot_function_type::ENTRIES),
    (mcrs_minecraft_keys::LOOT_NBT_PROVIDER_TYPE.location(), mcrs_minecraft_keys::loot_nbt_provider_type::ENTRIES),
    (mcrs_minecraft_keys::LOOT_POOL_ENTRY_TYPE.location(), mcrs_minecraft_keys::loot_pool_entry_type::ENTRIES),
    (mcrs_minecraft_keys::LOOT_SCORE_PROVIDER_TYPE.location(), mcrs_minecraft_keys::loot_score_provider_type::ENTRIES),
    (mcrs_minecraft_keys::MAP_DECORATION_TYPE.location(), mcrs_minecraft_keys::map_decoration_type::ENTRIES),
    (mcrs_minecraft_keys::MEMORY_MODULE_TYPE.location(), mcrs_minecraft_keys::memory_module_type::ENTRIES),
    (mcrs_minecraft_keys::MENU.location(), mcrs_minecraft_keys::menu::ENTRIES),
    (mcrs_minecraft_keys::MOB_EFFECT.location(), mcrs_minecraft_keys::mob_effect::ENTRIES),
    (mcrs_minecraft_keys::NUMBER_FORMAT_TYPE.location(), mcrs_minecraft_keys::number_format_type::ENTRIES),
    (mcrs_minecraft_keys::OUTGOING_RPC_METHODS.location(), mcrs_minecraft_keys::outgoing_rpc_methods::ENTRIES),
    (mcrs_minecraft_keys::PARTICLE_TYPE.location(), mcrs_minecraft_keys::particle_type::ENTRIES),
    (mcrs_minecraft_keys::PERMISSION_CHECK_TYPE.location(), mcrs_minecraft_keys::permission_check_type::ENTRIES),
    (mcrs_minecraft_keys::PERMISSION_TYPE.location(), mcrs_minecraft_keys::permission_type::ENTRIES),
    (mcrs_minecraft_keys::POINT_OF_INTEREST_TYPE.location(), mcrs_minecraft_keys::point_of_interest_type::ENTRIES),
    (mcrs_minecraft_keys::POS_RULE_TEST.location(), mcrs_minecraft_keys::pos_rule_test::ENTRIES),
    (mcrs_minecraft_keys::POSITION_SOURCE_TYPE.location(), mcrs_minecraft_keys::position_source_type::ENTRIES),
    (mcrs_minecraft_keys::POTION.location(), mcrs_minecraft_keys::potion::ENTRIES),
    (mcrs_minecraft_keys::RECIPE_BOOK_CATEGORY.location(), mcrs_minecraft_keys::recipe_book_category::ENTRIES),
    (mcrs_minecraft_keys::RECIPE_DISPLAY.location(), mcrs_minecraft_keys::recipe_display::ENTRIES),
    (mcrs_minecraft_keys::RECIPE_SERIALIZER.location(), mcrs_minecraft_keys::recipe_serializer::ENTRIES),
    (mcrs_minecraft_keys::RECIPE_TYPE.location(), mcrs_minecraft_keys::recipe_type::ENTRIES),
    (mcrs_minecraft_keys::RULE_BLOCK_ENTITY_MODIFIER.location(), mcrs_minecraft_keys::rule_block_entity_modifier::ENTRIES),
    (mcrs_minecraft_keys::RULE_TEST_TYPE.location(), mcrs_minecraft_keys::rule_test_type::ENTRIES),
    (mcrs_minecraft_keys::SENSOR_TYPE.location(), mcrs_minecraft_keys::sensor_type::ENTRIES),
    (mcrs_minecraft_keys::SLOT_DISPLAY.location(), mcrs_minecraft_keys::slot_display::ENTRIES),
    (mcrs_minecraft_keys::SLOT_SOURCE_TYPE.location(), mcrs_minecraft_keys::slot_source_type::ENTRIES),
    (mcrs_minecraft_sound::keys::SOUND_EVENT.location(), mcrs_minecraft_sound::keys::sound_event::ENTRIES),
    (mcrs_minecraft_keys::SPAWN_CONDITION_TYPE.location(), mcrs_minecraft_keys::spawn_condition_type::ENTRIES),
    (mcrs_minecraft_keys::STAT_TYPE.location(), mcrs_minecraft_keys::stat_type::ENTRIES),
    (mcrs_minecraft_keys::TEST_ENVIRONMENT_DEFINITION_TYPE.location(), mcrs_minecraft_keys::test_environment_definition_type::ENTRIES),
    (mcrs_minecraft_keys::TEST_FUNCTION.location(), mcrs_minecraft_keys::test_function::ENTRIES),
    (mcrs_minecraft_keys::TEST_INSTANCE_TYPE.location(), mcrs_minecraft_keys::test_instance_type::ENTRIES),
    (mcrs_minecraft_keys::TICKET_TYPE.location(), mcrs_minecraft_keys::ticket_type::ENTRIES),
    (mcrs_minecraft_keys::TRIGGER_TYPE.location(), mcrs_minecraft_keys::trigger_type::ENTRIES),
    (mcrs_minecraft_keys::VILLAGER_PROFESSION.location(), mcrs_minecraft_keys::villager_profession::ENTRIES),
    (mcrs_minecraft_keys::VILLAGER_TYPE.location(), mcrs_minecraft_keys::villager_type::ENTRIES),
    (mcrs_minecraft_keys::BIOME_SOURCE.location(), mcrs_minecraft_keys::biome_source::ENTRIES),
    (mcrs_minecraft_keys::BLOCK_STATE_PROVIDER_TYPE.location(), mcrs_minecraft_keys::block_state_provider_type::ENTRIES),
    (mcrs_minecraft_keys::CARVER_TYPE.location(), mcrs_minecraft_keys::carver_type::ENTRIES),
    (mcrs_minecraft_keys::CHUNK_GENERATOR.location(), mcrs_minecraft_keys::chunk_generator::ENTRIES),
    (mcrs_minecraft_keys::DENSITY_FUNCTION_TYPE.location(), mcrs_minecraft_keys::density_function_type::ENTRIES),
    (mcrs_minecraft_keys::FEATURE_SIZE_TYPE.location(), mcrs_minecraft_keys::feature_size_type::ENTRIES),
    (mcrs_minecraft_keys::FEATURE_TYPE.location(), mcrs_minecraft_keys::feature_type::ENTRIES),
    (mcrs_minecraft_keys::FOLIAGE_PLACER_TYPE.location(), mcrs_minecraft_keys::foliage_placer_type::ENTRIES),
    (mcrs_minecraft_keys::MATERIAL_CONDITION_TYPE.location(), mcrs_minecraft_keys::material_condition_type::ENTRIES),
    (mcrs_minecraft_keys::MATERIAL_RULE_TYPE.location(), mcrs_minecraft_keys::material_rule_type::ENTRIES),
    (mcrs_minecraft_keys::PLACEMENT_MODIFIER_TYPE.location(), mcrs_minecraft_keys::placement_modifier_type::ENTRIES),
    (mcrs_minecraft_keys::POOL_ALIAS_BINDING.location(), mcrs_minecraft_keys::pool_alias_binding::ENTRIES),
    (mcrs_minecraft_keys::ROOT_PLACER_TYPE.location(), mcrs_minecraft_keys::root_placer_type::ENTRIES),
    (mcrs_minecraft_keys::STRUCTURE_PIECE.location(), mcrs_minecraft_keys::structure_piece::ENTRIES),
    (mcrs_minecraft_keys::STRUCTURE_PLACEMENT.location(), mcrs_minecraft_keys::structure_placement::ENTRIES),
    (mcrs_minecraft_keys::STRUCTURE_POOL_ELEMENT.location(), mcrs_minecraft_keys::structure_pool_element::ENTRIES),
    (mcrs_minecraft_keys::STRUCTURE_PROCESSOR.location(), mcrs_minecraft_keys::structure_processor::ENTRIES),
    (mcrs_minecraft_keys::STRUCTURE_TYPE.location(), mcrs_minecraft_keys::structure_type::ENTRIES),
    (mcrs_minecraft_keys::TREE_DECORATOR_TYPE.location(), mcrs_minecraft_keys::tree_decorator_type::ENTRIES),
    (mcrs_minecraft_keys::TRUNK_PLACER_TYPE.location(), mcrs_minecraft_keys::trunk_placer_type::ENTRIES),
];

#[rustfmt::skip]
pub fn bindings() -> impl Iterator<Item = TypeBinding> {
    std::iter::empty()
        .chain(mcrs_minecraft_entity::keys::bindings())
        .chain(mcrs_minecraft_environment::keys::bindings())
        .chain(mcrs_minecraft_item::keys::bindings())
        .chain(mcrs_minecraft_keys::bindings())
        .chain(mcrs_minecraft_sound::keys::bindings())
}
